Repository Ignitus/Ignitus-client, pull requests merged in 2018-11, with the labels that each got.

#157 Scroll effect added
  package-lock.json
  src/ignitus-Introduction/Components/Introduction.js
  src/ignitus-Navigation/Components/Navigation.js
Labels: PR: reviewed-approved

#162 added structure for documentation
  .gitignore
  docs/Contributing.mdx
  docs/Local_Installation.mdx
  docs/getting_started.mdx
  package.json
  yarn.lock
Labels: PR: reviewed-approved

#159 Implement Aboutus and Team UI in ReactJS
  public/images/about/about-us.png
  public/images/about/avatar-bertha.png
  public/images/about/avatar-eugene.png
  public/images/about/avatar-george.png
  public/images/about/avatar-grant.png
  public/images/about/avatar-lauren.png
  public/images/about/avatar-melanie.png
  public/images/about/avatar-nelson.png
  public/images/about/avatar-robert.png
  public/images/split-blue-background.png
  src/ignitus-About/Components/About.js
  src/ignitus-About/Styles/style.scss
  src/ignitus-Contributors/Components/Contributors.js
  src/ignitus-GetStarted/Components/GetStarted.js
  src/ignitus-Introduction/Components/Introduction.js
  src/ignitus-Introduction/Styles/style.scss
  src/ignitus-Partners/Components/Partners.js
  src/ignitus-Partners/Styles/style.scss
  src/ignitus-Routes/publicRoutes.js
  src/ignitus-SignUp/Components/Signup.js
  src/ignitus-Team/Components/Constants.js
  src/ignitus-Team/Components/Team.js
  src/ignitus-Team/Components/index.js
  src/ignitus-Team/Styles/style.scss
  src/ignitus-Team/actionTypes.js
  src/ignitus-Team/actions.js
  src/ignitus-Team/constants.js
  src/ignitus-Team/index.js
  src/ignitus-Team/reducers.js
  src/ignitus-Team/sagas.js
  src/ignitus-Team/selectors.js
  src/shared/styles/ignitus-base.scss
  src/shared/styles/ignitus-tokens.scss
  src/shared/styles/ignitus-utilities.scss
Labels: PR: unreviewed

#168 Changed Contributors and added hex codes
  package-lock.json
  public/index.html
  src/ignitus-About/Components/About.js
  src/ignitus-About/Styles/style.scss
  src/ignitus-Assets/Images/Cards/expert.png
  src/ignitus-Assets/Images/Cards/expert1.png
  src/ignitus-Assets/Images/Cards/intern.png
  src/ignitus-Assets/Images/Cards/intern1.png
  src/ignitus-Assets/Images/Cards/offer.png
  src/ignitus-Assets/Images/Cards/offer1.png
  src/ignitus-Assets/Images/Logos/black_logo.png
  src/ignitus-Assets/Images/Logos/logo white bg.png
  src/ignitus-Assets/Images/Section/communityIcon.png
  src/ignitus-Assets/Images/Section/coursesIcon.png
  src/ignitus-Assets/Images/Section/internshipIcon.png
  src/ignitus-Assets/Images/partnersLogo/gsLogo.png
  src/ignitus-Assets/Images/partnersLogo/leanLogo.png
  src/ignitus-Assets/Images/partnersLogo/progateLogo.jpg
  src/ignitus-Assets/Images/partnersLogo/sugarlabsLogo.png
  src/ignitus-Assets/Images/partnersLogo/systersLogo.png
  src/ignitus-Assets/Images/partnersLogo/wootechLogo.png
  src/ignitus-Assets/Images/prof.png
  src/ignitus-Assets/Images/universityLogos/cmuLogo.png
  src/ignitus-Assets/Images/universityLogos/harvardLogo.png
  src/ignitus-Assets/Images/universityLogos/mitLogo.png
  src/ignitus-Assets/Images/universityLogos/oxfordLogo.png
  src/ignitus-Assets/Images/universityLogos/princetonLogo.png
  src/ignitus-Assets/Images/universityLogos/stanfordLogo.png
  src/ignitus-Assets/Images/universityLogos/ucbLogo.png
  src/ignitus-Assets/Images/universityLogos/yaleLogo.png
  src/ignitus-Contributors/Components/Contributors.js
  src/ignitus-Contributors/Styles/style.scss
  src/ignitus-Footer/Components/Constants.js
  src/ignitus-Footer/Components/Footer.js
  src/ignitus-Footer/Styles/style.scss
  src/ignitus-GetStarted/Components/GetStarted.js
  src/ignitus-Introduction/Components/Constants.js
  src/ignitus-Navigation/Components/Constants.js
  src/ignitus-Navigation/Components/Navigation.js
  src/ignitus-Partners/Components/Partners.js
  src/ignitus-Partners/Styles/style.scss
  src/ignitus-ProfessorLogin/Components/Constants.js
  src/ignitus-ProfessorLogin/Components/login.js
  src/ignitus-ProfessorSignUp/Components/Constants.js
  src/ignitus-ProfessorSignUp/Components/Signup.js
  src/ignitus-StudentLogin/Components/Constants.js
  src/ignitus-StudentLogin/Components/Login.js
  src/ignitus-StudentSignUp/Components/Constants.js
  src/ignitus-StudentSignUp/Components/Signup.js
  src/ignitus-Team/Components/Constants.js
  src/ignitus-Team/Components/Data.js
  src/ignitus-Team/Components/Team.js
  src/ignitus-Team/Styles/style.scss
  src/ignitus-Testimonial/Styles/style.scss
  src/ignitus-WhatWeDo/Components/Data/constants.js
  src/shared/styles/ignitus-tokens.scss
Labels: PR: unreviewed

#178 Padding added
  src/ignitus-WhatWeDo/Components/CardLayout.js
Labels: PR: reviewed-approved

#182 Enhanced Partner image/logo styles on landing page #173
  src/ignitus-About/Components/About.js
  src/ignitus-Contributors/Components/Contributors.js
  src/ignitus-Contributors/Styles/style.scss
  src/ignitus-Partners/Components/Partners.js
  src/ignitus-Partners/Styles/style.scss
  src/ignitus-Team/Components/Team.js
  src/ignitus-Team/Styles/style.scss
Labels: PR: reviewed-changes-requested
