Repository Ignitus/Ignitus-client, pull requests merged in 2019-12, with the labels that each got.

#394 Create stale.yml
  .github/workflows/stale.yml
Labels: PR: unreviewed

#402 deployment 🚀 bug fix.
  src/ignitus-Api/constants.js
Labels: PR: unreviewed

#317 fix: Bug in nav bar
  src/ignitus-Navigation/Styles/style.scss
Labels: PR: reviewed-approved, no-pr-activity

#405 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: PR: unreviewed

#455 Code refactoring. ★
   jest.config.js
  .eslintrc
  package-lock.json
  package.json
  src/ignitus-About/Components/About.js
  src/ignitus-Dashboard-Chatlist/Components/Constants.js
  src/ignitus-Dashboard-Chatlist/reducers.js
  src/ignitus-Dashboard-Header/constants.js
  src/ignitus-Dashboard-Profile-Section/reducers.js
  src/ignitus-Dashboard-Sidebar/reducers.js
  src/ignitus-Dashboard-View-Post/reducers.js
  src/ignitus-Dashboard-Write-Post/reducers.js
  src/ignitus-Footer/Components/Footer.test.js
  src/ignitus-Footer/Components/__snapshots__/Footer.test.js.snap
  src/ignitus-GetStarted/reducers.js
  src/ignitus-Helpers/ScrollToTopOnMount.js
  src/ignitus-Introduction/reducers.js
  src/ignitus-Navigation/Components/Navigation.js
  src/ignitus-Student-Dashboard-MenuItems/reducers.js
  src/ignitus-StudentLogin/Components/Login.js
  src/ignitus-StudentLogin/actions.js
  src/ignitus-StudentLogin/selectors.js
  src/ignitus-StudentSignUp/Components/Signup.js
  src/ignitus-StudentSignUp/actions.js
  src/ignitus-StudentSignUp/selectors.js
  src/ignitus-Team/actions.js
  src/ignitus-Team/selectors.js
  src/ignitus-WhatWeDo/Components/CardLayout.test.js
  src/ignitus-WhatWeDo/Components/__snapshots__/CardLayout.test.js.snap
Labels: PR: unreviewed

#457 Prettierrc configuration updated ✔️
  .prettierrc
Labels: PR: unreviewed

#458 bug fix 🚀
  src/ignitus-Navigation/Components/Navigation.js
Labels: PR: unreviewed

#460 Added sentry for real-time err monitoring ★
  package-lock.json
  package.json
  src/index.js
Labels: PR: unreviewed

#474 Team & Testimonials component migration to react-hooks.
  src/ignitus-Team/Components/Team.js
  src/ignitus-Testimonial/Components/Testimonial.js
  src/ignitus-Testimonial/Styles/style.scss
Labels: PR: unreviewed, migration

#480 Migrated CoreTeam => Hook ★
  package.json
  src/ignitus-CoreTeam/Components/Data.js
  src/ignitus-CoreTeam/Components/Team.js
  src/ignitus-Footer/Components/Footer.js
  src/ignitus-Navigation/Components/Navigation.js
  src/ignitus-Routes/privateRoute.js
  src/ignitus-Routes/protectedRoutes.js
  src/ignitus-StudentLogin/Components/Login.js
  src/ignitus-StudentSignUp/Components/Signup.js
  src/ignitus-Team/Components/Team.js
Labels: PR: unreviewed, migration
