Repository Ignitus/Ignitus-client, pull requests merged in 2020-03, with the labels that each got.

#568 Top margin reduced fixes issue #549
  src/ignitus-CoreTeam/Styles/index.ts
Labels: GSSOC'20, PR: reviewed-approved

#571 client-login downtime fix 🔨
  src/ignitus-StudentLogin/sagas.js
Labels: PR: unreviewed

#576 Added fix to issue 572, testimonials hide up in mobile devices
  src/ignitus-Testimonial/Styles/style.scss
Labels: GSSOC'20, PR: unreviewed, easy

#555 Fixed signup page styling for mobile devices.
  src/ignitus-Common-Auth-Student-Prof/Components/commonLoginUI.js
  src/ignitus-Common-Auth-Student-Prof/Components/commonSignUpUI.js
  src/ignitus-Common-Auth-Student-Prof/Styles/style.scss
Labels: GSSOC'20, PR: reviewed-approved, PR: unreviewed, medium

#577 Issue fix 574
  src/ignitus-Footer/Styles/style.scss
  src/ignitus-GetStarted/Styles/style.scss
  src/ignitus-Introduction/Styles/style.scss
Labels: PR: reviewed-approved, gssoc20

#566 Update contribution guidelines
  .github/CONTRIBUTION/CONTRIBUTION.md
Labels: PR: reviewed-approved

#586 master > develop 🧨
  src/ignitus-ProfessorSignUp/Components/Signup.js
Labels: PR: unreviewed

#588 Added TypeScript support with Hound
  .hound.yml
Labels: PR: reviewed-approved

#590 Restrict Contributors to 14 value and show all on github link
  src/ignitus-Api/constants.ts
  src/ignitus-Team/Components/Team.tsx
  src/ignitus-Team/Styles/index.ts
Labels: PR: reviewed-approved, enhancement, gssoc20, medium

#548 feat: Migrate common-auth-student-prof files to TS
  src/ignitus-Common-Auth-Student-Prof/Components/Constants.js
  src/ignitus-Common-Auth-Student-Prof/Components/commonLoginRegister.tsx
  src/ignitus-Common-Auth-Student-Prof/Components/commonLoginUI.js
  src/ignitus-Common-Auth-Student-Prof/Components/commonSignUpUI.js
  src/ignitus-Common-Auth-Student-Prof/Components/constants.ts
  src/ignitus-Common-Auth-Student-Prof/Components/createSignInPage.tsx
  src/ignitus-Routes/publicRoutes.js
Labels: PR: reviewed-approved, gssoc20, medium

#593 dashboard ui:navigator added
  package-lock.json
  src/ignitus-Shared/Components/Dashboard/SideNavigation.js
  src/ignitus-Shared/Components/Dashboard/style.scss
  src/ignitus-Shared/styles/ignitus-components-common.scss
  src/ignitus-Shared/styles/ignitus-tokens.scss
  src/ignitus-Student-Dashboard/Components/Dashboard.js
Labels: PR: reviewed-approved, gssoc20, medium

#598 issue #578 Error message UI fix
  .github/CONTRIBUTION/CONTRIBUTION.md
  src/ignitus-Api/constants.ts
  src/ignitus-Shared/Components/errorBoundary/index.js
Labels: PR: unreviewed

#620 Master > Develop 🧨
  public/images/about/avatar-bertha.png
  public/images/about/avatar-eugene.png
  public/images/about/avatar-george.png
  public/images/about/avatar-grant.png
  public/images/about/avatar-lauren.png
  public/images/about/avatar-nelson.png
  public/images/about/avatar-robert.png
  src/ignitus-Assets/Images/Resume.svg
  src/ignitus-Assets/Images/black-logo.svg
  src/ignitus-Assets/Images/commonAuthUIProf.png
  src/ignitus-Assets/Images/ignitus-logo.png
  src/ignitus-Assets/Images/ignitus-torch.png
  src/ignitus-Assets/Images/nav-logo.svg
  src/ignitus-Assets/Images/professorAuth.svg
  src/ignitus-Assets/Images/studentAuth.svg
  src/ignitus-Assets/Images/torch.svg
  src/ignitus-Assets/Images/white-logo.png
  src/ignitus-Authentication/ignitus-ProfessorLogin/Components/login.js
  src/ignitus-Authentication/ignitus-StudentLogin/Components/Login.js
  src/ignitus-Dashboard/ignitus-Student-Dashboard/Components/Dashboard.js
  src/ignitus-Navigation/Components/Navigation.test.js
  src/ignitus-Routes/privateRoutes/index.js
  src/ignitus-Routes/protectedRoutes/index.js
  src/ignitus-Routes/publicRoutes/index.js
  src/ignitus-Shared/Components/ignitus-AuthenticationComponents/Login/Constants.js
  src/ignitus-Shared/Components/ignitus-AuthenticationComponents/Login/Login.js
  src/ignitus-Shared/Components/ignitus-DashBoardComponents/DashboardSideNavigation/SideNavigation.js
  src/ignitus-Shared/Components/ignitus-DashBoardComponents/DashboardSideNavigation/style.scss
  src/ignitus-Shared/Components/ignitus-Footer/Components/Constants.js
  src/ignitus-Shared/Components/ignitus-Footer/Components/Footer.js
  src/ignitus-Shared/Components/ignitus-Footer/Components/index.js
  src/ignitus-Shared/Components/ignitus-Footer/Containers/footerContainer.js
  src/ignitus-Shared/Components/ignitus-Footer/Styles/style.scss
  src/ignitus-Shared/Components/ignitus-Footer/actionTypes.js
  src/ignitus-Shared/Components/ignitus-Footer/actions.js
  src/ignitus-Shared/Components/ignitus-Footer/constants.js
  src/ignitus-Shared/Components/ignitus-Footer/index.js
  src/ignitus-Shared/Components/ignitus-Footer/reducers.js
  src/ignitus-Shared/Components/ignitus-Footer/sagas.js
  src/ignitus-Shared/Components/ignitus-Footer/selectors.js
  src/ignitus-Shared/Components/ignitus-Navigation/Components/Constants.js
  src/ignitus-Shared/Components/ignitus-Navigation/Components/Navigation.js
  src/ignitus-Shared/Components/ignitus-Navigation/Components/Navigation.test.js
  src/ignitus-Shared/Components/ignitus-Navigation/Components/index.js
  src/ignitus-Shared/Components/ignitus-Navigation/Containers/navigationContainer.js
  src/ignitus-Shared/Components/ignitus-Navigation/Styles/style.scss
  src/ignitus-Shared/Components/ignitus-Navigation/actionTypes.js
  src/ignitus-Shared/Components/ignitus-Navigation/actions.js
  src/ignitus-Shared/Components/ignitus-Navigation/constants.js
  src/ignitus-Shared/Components/ignitus-Navigation/index.js
  src/ignitus-Shared/Components/ignitus-Navigation/reducers.js
  src/ignitus-Shared/Components/ignitus-Navigation/sagas.js
  src/ignitus-Shared/Components/ignitus-Navigation/selectors.js
  src/ignitus-Shared/Components/ignitus-NotFound/Styles/style.scss
  src/ignitus-Shared/Components/ignitus-NotFound/index.js
Labels: enhancement, release

#622 issue #616 improvements in CONTRIBUTION.md
  .github/CONTRIBUTION/CONTRIBUTION.md
Labels: PR: reviewed-approved

#625 Master > Develop
  .github/CONTRIBUTION/CONTRIBUTION.md
Labels: PR: unreviewed

#626 Client updated as per upcoming changes on rest-api. ☘️🚀☘️.
  src/ignitus-Api/constants.ts
  src/ignitus-HomePage/ignitus-Testimonial/Components/Testimonial.js
Labels: PR: unreviewed

#627 Authentication broken fix 🔨☘️
  src/ignitus-Authentication/ignitus-StudentLogin/sagas.js
  src/ignitus-HomePage/ignitus-Testimonial/Components/Testimonial.js
  src/ignitus-Shared/Components/ignitus-AuthenticationComponents/Login/Login.js
Labels: PR: unreviewed

#630 migrate ignitus-Introduction to TS
  src/ignitus-HomePage/ignitus-Introduction/Components/Constants.js
  src/ignitus-HomePage/ignitus-Introduction/Components/Introduction.tsx
  src/ignitus-HomePage/ignitus-Introduction/Components/index.ts
  src/ignitus-HomePage/ignitus-Introduction/Containers/introductionContainer.js
  src/ignitus-HomePage/ignitus-Introduction/Containers/introductionContainer.ts
  src/ignitus-HomePage/ignitus-Introduction/actionTypes.js
  src/ignitus-HomePage/ignitus-Introduction/actionTypes.ts
  src/ignitus-HomePage/ignitus-Introduction/actions.js
  src/ignitus-HomePage/ignitus-Introduction/actions.ts
  src/ignitus-HomePage/ignitus-Introduction/constants.js
  src/ignitus-HomePage/ignitus-Introduction/constants.ts
  src/ignitus-HomePage/ignitus-Introduction/index.ts
  src/ignitus-HomePage/ignitus-Introduction/reducers.js
  src/ignitus-HomePage/ignitus-Introduction/reducers.ts
  src/ignitus-HomePage/ignitus-Introduction/sagas.ts
  src/ignitus-HomePage/ignitus-Introduction/selectors.js
  src/ignitus-HomePage/ignitus-Introduction/selectors.ts
Labels: PR: reviewed-approved

#636 ⭐️ add internship list view
  src/ignitus-AboutPage/ignitus-Team/Styles/index.ts
  src/ignitus-Routes/publicRoutes/index.js
  src/ignitus-Shared/Components/InternshipList/OppurtunityList.tsx
  src/ignitus-Shared/Components/InternshipList/index.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Assets/ignitus-Icons/applyIcon/applyIcon.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Assets/ignitus-Icons/applyIcon/index.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Templates/ignitus-DashboardSideNavigation/style.scss
  src/ignitus-Shared/ignitus-DesignSystem/shared.ts
Labels: PR: reviewed-approved, onHold

#640 Added side navigation bar to user settings page. ☘️
  src/ignitus-Routes/publicRoutes/index.js
  src/ignitus-Shared/Components/InternshipList/Components/OppurtunityList.tsx
  src/ignitus-Shared/Components/InternshipList/styles.ts
  src/ignitus-Shared/Components/UserSettingsSideNavigation/Components/index.tsx
  src/ignitus-Shared/Components/UserSettingsSideNavigation/style.ts
  src/ignitus-UserInterfaceKit/Components/index.tsx
Labels: PR: unreviewed

#641 #634 🔨
  src/ignitus-AboutPage/ignitus-CoreTeam/Components/team.tsx
  src/ignitus-AboutPage/ignitus-CoreTeam/Styles/index.ts
  src/ignitus-Routes/protectedRoutes/index.js
  src/ignitus-Routes/publicRoutes/index.js
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Assets/ignitus-Icons/icon.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Layout/ignitus-NotFound/Components/index.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Layout/ignitus-NotFound/Styles/style.scss
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Layout/ignitus-NotFound/index.js
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Layout/ignitus-NotFound/style.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-OppurtunityList/Components/OppurtunityList.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-OppurtunityList/styles.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-UserSettingsSideNavigation/Components/index.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-UserSettingsSideNavigation/style.ts
  src/ignitus-Shared/types/iconsTypes/enums.ts
  src/ignitus-UserInterfaceKit/Components/index.tsx
Labels: PR: unreviewed

#637 created site under build page UI component
  src/ignitus-Authentication/ignitus-CommonAuthentication/Components/commonLoginRegister.tsx
  src/ignitus-Authentication/ignitus-CommonAuthentication/Components/constants.ts
  src/ignitus-Authentication/ignitus-CommonAuthentication/Components/createSignInPage.tsx
  src/ignitus-Authentication/ignitus-CommonAuthentication/Styles/style.scss
  src/ignitus-Dashboard/ignitus-DashboardHeader/Components/dashBoardHeader.js
  src/ignitus-Dashboard/ignitus-DashboardHeader/Components/index.js
  src/ignitus-Dashboard/ignitus-DashboardHeader/Containers/dashBoardHeaderContainer.js
  src/ignitus-Dashboard/ignitus-DashboardHeader/Containers/index.js
  src/ignitus-Dashboard/ignitus-DashboardHeader/Styles/style.scss
  src/ignitus-Dashboard/ignitus-DashboardHeader/actionTypes.js
  src/ignitus-Dashboard/ignitus-DashboardHeader/actions.js
  src/ignitus-Dashboard/ignitus-DashboardHeader/constants.js
  src/ignitus-Dashboard/ignitus-DashboardHeader/index.js
  src/ignitus-Dashboard/ignitus-DashboardHeader/reducers.js
  src/ignitus-Dashboard/ignitus-DashboardHeader/sagas.js
  src/ignitus-Dashboard/ignitus-DashboardHeader/selectors.js
  src/ignitus-Dashboard/ignitus-Student-Dashboard/Components/Dashboard.js
  src/ignitus-Dashboard/ignitus-Student-Dashboard/Styles/style.scss
  src/ignitus-Dashboard/ignitus-StudentDashboard/Components/Dashboard.js
  src/ignitus-Dashboard/ignitus-StudentDashboard/Components/index.js
  src/ignitus-Dashboard/ignitus-StudentDashboard/Containers/dashboardContainer.js
  src/ignitus-Dashboard/ignitus-StudentDashboard/Styles/style.scss
  src/ignitus-Dashboard/ignitus-StudentDashboard/actionTypes.js
  src/ignitus-Dashboard/ignitus-StudentDashboard/actions.js
  src/ignitus-Dashboard/ignitus-StudentDashboard/constants.js
  src/ignitus-Dashboard/ignitus-StudentDashboard/index.js
  src/ignitus-Dashboard/ignitus-StudentDashboard/reducers.js
  src/ignitus-Dashboard/ignitus-StudentDashboard/sagas.js
  src/ignitus-Dashboard/ignitus-StudentDashboard/selectors.js
  src/ignitus-Routes/protectedRoutes/index.js
  src/ignitus-Routes/publicRoutes/index.js
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Assets/ignitus-Images/img-Png/underContruction.png
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/atoms.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Layout/ignitus-UnderContruction/Components/index.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Layout/ignitus-UnderContruction/styles.ts
  src/ignitus-UserInterfaceKit/Components/index.tsx
Labels: PR: unreviewed

#655 Migrated ignitus-GetStarted files to TS
  src/ignitus-HomePage/ignitus-GetStarted/Components/GetStarted.tsx
  src/ignitus-HomePage/ignitus-GetStarted/Components/index.ts
  src/ignitus-HomePage/ignitus-GetStarted/Containers/getstartedContainer.js
  src/ignitus-HomePage/ignitus-GetStarted/Containers/getstartedContainer.ts
  src/ignitus-HomePage/ignitus-GetStarted/actionTypes.js
  src/ignitus-HomePage/ignitus-GetStarted/actionTypes.ts
  src/ignitus-HomePage/ignitus-GetStarted/actions.js
  src/ignitus-HomePage/ignitus-GetStarted/actions.ts
  src/ignitus-HomePage/ignitus-GetStarted/index.ts
  src/ignitus-HomePage/ignitus-GetStarted/reducers.js
  src/ignitus-HomePage/ignitus-GetStarted/reducers.ts
  src/ignitus-HomePage/ignitus-GetStarted/sagas.ts
  src/ignitus-HomePage/ignitus-GetStarted/selectors.js
  src/ignitus-HomePage/ignitus-GetStarted/selectors.ts
Labels: PR: reviewed-approved

#653 Added replacement for lodash methods under ignitus-UtilityFunctions
  src/ignitus-Authentication/ignitus-StudentLogin/Components/Login.jsx
  src/ignitus-Authentication/ignitus-StudentLogin/actions.js
  src/ignitus-Authentication/ignitus-StudentLogin/selectors.js
  src/ignitus-Authentication/ignitus-StudentSignUp/Components/Signup.jsx
  src/ignitus-Authentication/ignitus-StudentSignUp/actions.js
  src/ignitus-Authentication/ignitus-StudentSignUp/selectors.js
  src/ignitus-UtilityFunctions/utilityFunctions.js
Labels: PR: reviewed-approved, gssoc20, onHold

#665 Added 3 svg icons
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Assets/ignitus-Icons/clearIcon/clearIcon.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Assets/ignitus-Icons/clearIcon/index.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Assets/ignitus-Icons/createIcon/createIcon.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Assets/ignitus-Icons/createIcon/index.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Assets/ignitus-Icons/locationOnIcon/index.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Assets/ignitus-Icons/locationOnIcon/locationOnIcon.tsx
  src/ignitus-Shared/ignitus-Utilities/Components/icon.tsx
  src/ignitus-Shared/types/iconsTypes/enums.ts
  src/ignitus-UserInterfaceBook/Components/Atoms/interfaceIcons/constants.ts
Labels: PR: reviewed-approved

#674 Added 8 SVG icons
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Assets/ignitus-Icons/facebookIcon/facebookIcon.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Assets/ignitus-Icons/facebookIcon/index.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Assets/ignitus-Icons/githubIcon/githubIcon.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Assets/ignitus-Icons/githubIcon/index.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Assets/ignitus-Icons/googlePlusIcon/googlePlusIcon.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Assets/ignitus-Icons/googlePlusIcon/index.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Assets/ignitus-Icons/graduationCapIcon/graduationCapIcon.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Assets/ignitus-Icons/graduationCapIcon/index.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Assets/ignitus-Icons/infoIcon/index.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Assets/ignitus-Icons/infoIcon/infoIcon.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Assets/ignitus-Icons/libraryBooksIcon/index.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Assets/ignitus-Icons/libraryBooksIcon/libraryBooksIcon.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Assets/ignitus-Icons/localLibraryIcon/index.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Assets/ignitus-Icons/localLibraryIcon/localLibraryIcon.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Assets/ignitus-Icons/pdfIcon/index.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Assets/ignitus-Icons/pdfIcon/pdfIcon.tsx
  src/ignitus-Shared/ignitus-Utilities/Components/icon.tsx
  src/ignitus-Shared/types/iconsTypes/enums.ts
  src/ignitus-UserInterfaceBook/Components/Atoms/interfaceIcons/constants.ts
Labels: PR: reviewed-approved

#658 Aggregation of signup components sharing same functionality
  src/ignitus-Authentication/ignitus-ProfessorLogin/Components/login.jsx
  src/ignitus-Authentication/ignitus-ProfessorSignUp/Components/Constants.js
  src/ignitus-Authentication/ignitus-ProfessorSignUp/Components/Signup.jsx
  src/ignitus-Authentication/ignitus-StudentLogin/Components/Login.jsx
  src/ignitus-Authentication/ignitus-StudentLogin/Styles/style.scss
  src/ignitus-Authentication/ignitus-StudentSignUpFlow/ignitus-StudentSignUp/Components/SignUp.tsx
  src/ignitus-Authentication/ignitus-StudentSignUpFlow/ignitus-StudentSignUp/Styles/style.scss
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Templates/ignitus-AuthenticationComponents/Login/Constants.js
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Templates/ignitus-SharedAuthentication/ignitus-sharedLogin/Components/SharedLogin.jsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Templates/ignitus-SharedAuthentication/ignitus-sharedLogin/constants.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Templates/ignitus-SharedAuthentication/ignitus-sharedLogin/types.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Templates/ignitus-SharedAuthentication/ignitus-sharedSignUp/Components/SharedSignUp.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Templates/ignitus-SharedAuthentication/ignitus-sharedSignUp/constants.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Templates/ignitus-SharedAuthentication/ignitus-sharedSignUp/types.ts
Labels: PR: unreviewed

#673 Search, account and Notification icons
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Assets/ignitus-Icons/SearchIcon/index.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Assets/ignitus-Icons/SearchIcon/searchIcon.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Assets/ignitus-Icons/accountCircleIcon/accountCircleIcon.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Assets/ignitus-Icons/accountCircleIcon/index.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Assets/ignitus-Icons/notificationIcon/index.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Assets/ignitus-Icons/notificationIcon/notificationIcon.tsx
  src/ignitus-Shared/ignitus-Utilities/Components/icon.tsx
  src/ignitus-Shared/types/iconsTypes/enums.ts
  src/ignitus-UserInterfaceBook/Components/Atoms/interfaceIcons/constants.ts
Labels: PR: unreviewed

#670 Interest Flow migrated to => Emotion. 🔨
  src/ignitus-Authentication/ignitus-StudentSignUpFlow/ignitus-InterestFlow/Components/InterestFlow.jsx
  src/ignitus-Authentication/ignitus-StudentSignUpFlow/ignitus-InterestFlow/Components/index.js
  src/ignitus-Authentication/ignitus-StudentSignUpFlow/ignitus-InterestFlow/Components/index.ts
  src/ignitus-Authentication/ignitus-StudentSignUpFlow/ignitus-InterestFlow/Styles/style.scss
  src/ignitus-Authentication/ignitus-StudentSignUpFlow/ignitus-InterestFlow/Styles/style.ts
  src/ignitus-Authentication/ignitus-StudentSignUpFlow/ignitus-WelcomeFlow/Components/WelcomeFlow.jsx
  src/ignitus-Authentication/ignitus-StudentSignUpFlow/ignitus-WelcomeFlow/Styles/style.ts
  src/ignitus-Routes/ignitus-PublicRoutes/index.tsx
  src/ignitus-Routes/ignitus-UserInterfaceBookRoutes/index.jsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/buttons.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultCheckbox/Components/defaultCheckbox.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultCheckbox/Components/index.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultCheckbox/styles.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultCheckbox/types.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultDropdown/Components/defaultDropdown.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultDropdown/Components/index.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultDropdown/constants.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultDropdown/styles.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultDropdown/types.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultlDropdown/style.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultlDropdown/types.ts
  src/ignitus-UserInterfaceBook/Components/Atoms/interfaceCheckBox/Components/index.ts
  src/ignitus-UserInterfaceBook/Components/Atoms/interfaceCheckBox/Components/interfaceCheckBox.tsx
  src/ignitus-UserInterfaceBook/Components/Atoms/interfaceCheckBox/constants.ts
  src/ignitus-UserInterfaceBook/Components/Atoms/interfaceCheckBox/styles.ts
  src/ignitus-UserInterfaceBook/Components/Atoms/interfaceDropDown/Components/interfaceDropDown.tsx
  src/ignitus-UserInterfaceBook/InterfaceSideNavigation/Components/interfaceSideNavigation.tsx
  src/ignitus-UserInterfaceBook/InterfaceSideNavigation/constants.ts
  src/ignitus-UserInterfaceBook/InterfaceSideNavigation/style.ts
Labels: PR: reviewed-approved

#677 Added default Input html element component.
  README.md
  src/ignitus-Routes/ignitus-UserInterfaceBookRoutes/index.jsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultInput/Components/defaultInput.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultInput/Components/index.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultInput/styles.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultInput/types.ts
  src/ignitus-UserInterfaceBook/InterfaceSideNavigation/constants.ts
  src/ignitus-UserInterfaceKit/Components/Atoms/interfaceInput/Components/index.ts
  src/ignitus-UserInterfaceKit/Components/Atoms/interfaceInput/Components/interfaceInput.tsx
  src/ignitus-UserInterfaceKit/Components/Atoms/interfaceInput/styles.ts
Labels: PR: unreviewed

#679 Email Flow migrated to => Emotion
  src/ignitus-Authentication/ignitus-StudentSignUpFlow/ignitus-EmailConfirmationFlow/Styles/style.scss
  src/ignitus-Authentication/ignitus-StudentSignUpFlow/ignitus-EmailFlow/Components/EmailFlow.jsx
  src/ignitus-Authentication/ignitus-StudentSignUpFlow/ignitus-EmailFlow/Components/EmailFlow.tsx
  src/ignitus-Authentication/ignitus-StudentSignUpFlow/ignitus-EmailFlow/Components/index.js
  src/ignitus-Authentication/ignitus-StudentSignUpFlow/ignitus-EmailFlow/Components/index.ts
  src/ignitus-Authentication/ignitus-StudentSignUpFlow/ignitus-EmailFlow/Styles/style.scss
  src/ignitus-Authentication/ignitus-StudentSignUpFlow/ignitus-EmailFlow/Styles/style.ts
  src/ignitus-Authentication/ignitus-StudentSignUpFlow/ignitus-InterestFlow/Components/InterestFlow.jsx
  src/ignitus-Authentication/ignitus-StudentSignUpFlow/ignitus-WelcomeFlow/Styles/style.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/buttons.ts
Labels: PR: unreviewed

#685 Email Confirmation Flow migrated to => Emotion
  src/ignitus-Authentication/ignitus-StudentSignUpFlow/ignitus-EmailConfirmationFlow/Components/EmailConfirmationFlow.jsx
  src/ignitus-Authentication/ignitus-StudentSignUpFlow/ignitus-EmailConfirmationFlow/Components/index.js
  src/ignitus-Authentication/ignitus-StudentSignUpFlow/ignitus-EmailConfirmationFlow/Components/index.ts
  src/ignitus-Authentication/ignitus-StudentSignUpFlow/ignitus-EmailConfirmationFlow/Styles/style.scss
  src/ignitus-Authentication/ignitus-StudentSignUpFlow/ignitus-EmailConfirmationFlow/Styles/style.ts
Labels: PR: reviewed-approved

#681 BS4 => Pure CSS Navigation Bar.
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-Navigation/Components/Navigation.jsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-Navigation/Styles/style.scss
Labels: PR: unreviewed, gssoc20, hard

#694 UI Kit changes 🎯
  package-lock.json
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/colors.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/typography.ts
  src/ignitus-UserInterfaceBook/Components/Atoms/interfaceColors/constants.ts
  src/ignitus-UserInterfaceBook/Components/Atoms/interfaceIcons/Components/interfaceIcons.tsx
  src/ignitus-UserInterfaceBook/Components/Atoms/interfaceTypography/Components/interfaceTypography.tsx
  src/ignitus-UserInterfaceBook/InterfaceSideNavigation/constants.ts
  src/ignitus-UserInterfaceBook/InterfaceSideNavigation/style.ts
Labels: PR: reviewed-approved

#693 Added opportunities saved layout. ★
  package-lock.json
  src/ignitus-AboutPage/ignitus-Team/Components/Team.tsx
  src/ignitus-Routes/ignitus-UserInterfaceBookRoutes/index.jsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Assets/ignitus-Images/img-Png/universityOfMelbourne.png
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Layout/ignitus-DashBoardOpportunity/Components/DashBoardOpportunity.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Layout/ignitus-DashBoardOpportunity/constants.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Layout/ignitus-DashBoardOpportunity/style.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Layout/ignitus-DashBoardOpportunity/types.ts
  src/ignitus-UserInterfaceBook/Components/Layouts/interfaceDashBoardOpportunity/Components/index.ts
  src/ignitus-UserInterfaceBook/Components/Layouts/interfaceDashBoardOpportunity/Components/interfaceDashBoardOpportunity.tsx
  src/ignitus-UserInterfaceBook/Components/Layouts/interfaceDashBoardOpportunity/constants.ts
  src/ignitus-UserInterfaceBook/Components/Layouts/interfaceDashBoardOpportunity/style.ts
  src/ignitus-UserInterfaceBook/Components/Layouts/interfaceDashBoardOpportunity/types.ts
  src/ignitus-UserInterfaceBook/Components/Organisms/interfaceCardLayout/Components/interfaceCardLayout.tsx
  src/ignitus-UserInterfaceBook/Components/Organisms/interfaceCardLayout/style.ts
  src/ignitus-UserInterfaceBook/InterfaceSideNavigation/constants.ts
Labels: PR: unreviewed

#689 Search Input UI ☘️
  src/ignitus-Routes/ignitus-UserInterfaceBookRoutes/index.jsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultSearchInput/Components/defaultSearchInput.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultSearchInput/Components/index.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultSearchInput/constants.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultSearchInput/styles.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultSearchInput/types.ts
  src/ignitus-UserInterfaceBook/Components/Atoms/interfaceCheckBox/Components/interfaceCheckBox.tsx
  src/ignitus-UserInterfaceBook/Components/Atoms/interfaceIcons/Components/interfaceIcons.tsx
  src/ignitus-UserInterfaceBook/Components/Atoms/interfaceSearchInput/Components/index.ts
  src/ignitus-UserInterfaceBook/Components/Atoms/interfaceSearchInput/Components/interfaceSearchInput.tsx
  src/ignitus-UserInterfaceBook/Components/Atoms/interfaceSearchInput/constants.ts
  src/ignitus-UserInterfaceBook/Components/Atoms/interfaceSearchInput/styles.ts
  src/ignitus-UserInterfaceBook/Components/Atoms/interfaceSearchInput/types.ts
Labels: PR: reviewed-approved

#699 Pure footer ★☘️🚀🎯
  src/ignitus-AboutPage/ignitus-About/Styles/index.ts
  src/ignitus-AboutPage/ignitus-CoreTeam/Styles/index.ts
  src/ignitus-Authentication/ignitus-StudentSignUpFlow/ignitus-InterestFlow/Styles/style.ts
  src/ignitus-Authentication/ignitus-StudentSignUpFlow/ignitus-WelcomeFlow/Styles/style.ts
  src/ignitus-HomePage/ignitus-Contributors/Styles/index.ts
  src/ignitus-HomePage/ignitus-WhatWeDo/Styles/index.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/atoms.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/media.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-Footer/Components/Constants.js
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-Footer/Components/Footer.jsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-Footer/Components/Footer.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-Footer/Components/index.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-Footer/Containers/footerContainer.js
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-Footer/Containers/footerContainer.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-Footer/Styles/style.scss
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-Footer/actionTypes.js
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-Footer/actionTypes.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-Footer/actions.js
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-Footer/actions.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-Footer/constants.js
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-Footer/constants.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-Footer/index.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-Footer/reducers.js
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-Footer/reducers.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-Footer/sagas.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-Footer/selectors.js
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-Footer/selectors.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-Footer/styles.ts
  src/ignitus-Shared/ignitus-DesignSystem/shared.ts
Labels: PR: unreviewed

#702 Separator UI 🎯
  README.md
  src/ignitus-Routes/ignitus-UserInterfaceBookRoutes/index.jsx
  src/ignitus-UserInterfaceBook/Components/Atoms/interfaceSeparator/Components /index.ts
  src/ignitus-UserInterfaceBook/Components/Atoms/interfaceSeparator/Components /interfaceSeparator.tsx
  src/ignitus-UserInterfaceBook/Components/Atoms/interfaceSeparator/styles.ts
Labels: PR: unreviewed

#704 Add Interface link in Footer
  src/ignitus-HomePage/ignitus-Testimonial/Styles/style.scss
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultSearchInput/styles.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-Footer/Components/Footer.tsx
Labels: PR: unreviewed

#708 Images 🌄 migration to GCP ⚓️
  src/ignitus-AboutPage/ignitus-About/Styles/index.ts
  src/ignitus-AboutPage/ignitus-About/constants.ts
  src/ignitus-AboutPage/ignitus-CoreTeam/constants.ts
  src/ignitus-Authentication/ignitus-CommonAuthenticationInterface/constants.ts
  src/ignitus-Authentication/ignitus-StudentSignUpFlow/ignitus-EmailConfirmationFlow/Components/EmailConfirmationFlow.jsx
  src/ignitus-Authentication/ignitus-StudentSignUpFlow/ignitus-EmailFlow/Components/EmailFlow.jsx
  src/ignitus-Authentication/ignitus-StudentSignUpFlow/ignitus-InterestFlow/Components/InterestFlow.jsx
  src/ignitus-Authentication/ignitus-StudentSignUpFlow/ignitus-StudentSignUp/constants.js
  src/ignitus-Authentication/ignitus-StudentSignUpFlow/ignitus-WelcomeFlow/Components/WelcomeFlow.jsx
  src/ignitus-Dashboard/ignitus-DashboardHeader/Components/dashBoardHeader.js
  src/ignitus-Dashboard/ignitus-DashboardHeader/constants.js
  src/ignitus-HomePage/ignitus-Contributors/constants.ts
  src/ignitus-HomePage/ignitus-Introduction/Styles/style.scss
  src/ignitus-HomePage/ignitus-Introduction/constants.ts
  src/ignitus-HomePage/ignitus-Partners/constants.ts
  src/ignitus-HomePage/ignitus-WhatWeDo/constants.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Assets/ignitus-Images/img-Png/interestsImage.png
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Assets/ignitus-Images/img-Png/profileImageMap.png
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Assets/ignitus-Images/img-Png/progressPage1.png
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Assets/ignitus-Images/img-Png/progressPage2.png
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Assets/ignitus-Images/img-Png/progressPage3.png
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Assets/ignitus-Images/img-Png/progressPage5.png
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Assets/ignitus-Images/img-Png/progressPage6.png
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Assets/ignitus-Images/img-Png/underContruction.png
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Assets/ignitus-Images/img-Png/universityOfMelbourne.png
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Assets/ignitus-Logos/logo-Png/IgnitusBlackLogo.png
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Assets/ignitus-Logos/logo-Png/IgnitusBlackLogoFull.png
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Assets/ignitus-Logos/logo-Png/IgnitusBlueLogoFull.png
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Assets/ignitus-Logos/logo-Png/IgnitusWhiteLogoFull.png
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Assets/ignitus-Logos/logo-Png/ignitusBlueLogo.png
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Assets/ignitus-Logos/logo-Png/ignitusWhiteLogo.png
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Layout/ignitus-UnderContruction/Components/index.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-Footer/constants.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-Footer/styles.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-Navigation/navigation.test.js
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-OppurtunityList/Components/OppurtunityList.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Templates/ignitus-Authentication/constants.ts
  src/ignitus-Shared/styles/ignitus-utilities.scss
  src/ignitus-UserInterfaceBook/Components/Layouts/interfaceSavedOpportunity/constants.ts
Labels: PR: unreviewed

#711 Clean SharedAuth component
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Templates/ignitus-Authentication/Components/SharedAuth.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Templates/ignitus-Authentication/Components/SplittedComponents/FormComponent/index.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Templates/ignitus-Authentication/Components/SplittedComponents/LoaderComponent/index.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Templates/ignitus-Authentication/Components/SplittedComponents/SideWrapperComponent/index.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Templates/ignitus-Authentication/Components/SplittedComponents/WrapperComponent/index.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Templates/ignitus-Authentication/Components/SplittedComponents/index.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Templates/ignitus-Authentication/types.ts
Labels: PR: unreviewed
