Repository Ignitus/Ignitus-client, pull requests merged in 2020-09, with the labels that each got.

#943 feat: Props update of ignitus-Notifications
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-Notifications/Components/index.test.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-Notifications/Components/index.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-Notifications/types.ts
  src/ignitus-UserInterfaceBook/Components/Organisms/interfaceNotifications/Components/index.tsx
Labels: PR: reviewed-approved

#903 fixed PasswordInput margin
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Templates/ignitus-Authentication/styles.ts
Labels: PR: partially-approved

#888 Added basicProfileDetails page and upload icon
  src/ignitus-Authentication/ignitus-StudentSignUpFlow/ignitus-BasicProfileFlow/Components/index.tsx
  src/ignitus-Authentication/ignitus-StudentSignUpFlow/ignitus-BasicProfileFlow/style.ts
  src/ignitus-Authentication/ignitus-StudentSignUpFlow/index.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Assets/ignitus-Icons/uploadIcon/index.tsx
  src/ignitus-Shared/ignitus-Utilities/Components/icon.tsx
  src/ignitus-Shared/types/iconsTypes/iconEnums.ts
  src/ignitus-UserInterfaceBook/Components/Atoms/interfaceIcons/constants.ts
Labels: PR: partially-approved

#927 added messageSettings component
  src/ignitus-Routes/ignitus-UserInterfaceBookRoutes/index.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultCheckbox/Components/__snapshots__/index.test.tsx.snap
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultCheckbox/Components/index.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultCheckbox/styles.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultCheckbox/types.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-MessageSettings/Components/index.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-MessageSettings/styles.ts
  src/ignitus-Shared/index.ts
  src/ignitus-UserInterfaceBook/Components/Organisms/interfaceMessageSettings/Components/index.tsx
  src/ignitus-UserInterfaceBook/InterfaceSideNavigation/constants.ts
Labels: PR: unreviewed
