Repository Ignitus/Ignitus-client, pull requests merged in 2020-07, with the labels that each got.

#897 Convert Ignitus loader into CSS
  src/ignitus-Routes/ignitus-UserInterfaceBookRoutes/index.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-Loader/Components/index.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-Loader/styles.ts
  src/ignitus-Shared/index.ts
  src/ignitus-UserInterfaceBook/Components/Atoms/interfaceLoader/Components/index.tsx
  src/ignitus-UserInterfaceBook/InterfaceSideNavigation/constants.ts
Labels: PR: partially-approved

#894 fix navbar issue
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-Navigation/Components/index.tsx
Labels: PR: partially-approved

#892 removed all useEffect warnings
  src/ignitus-AboutPage/ignitus-Team/Components/index.tsx
  src/ignitus-Authentication/ignitus-ProfessorSignUp/Components/index.tsx
  src/ignitus-Authentication/ignitus-StudentSignUpFlow/ignitus-StudentSignUp/Components/index.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultIconInput/Components/defaultIconInput/index.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultIconInput/Components/defaultPasswordInput/index.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-secondaryDropDown/Components/index.tsx
Labels: PR: partially-approved

#887 Replaced SignUp progress image with Component
  src/ignitus-Authentication/ignitus-StudentSignUpFlow/ignitus-EmailConfirmationFlow/Components/index.tsx
  src/ignitus-Authentication/ignitus-StudentSignUpFlow/ignitus-EmailFlow/Components/index.tsx
  src/ignitus-Authentication/ignitus-StudentSignUpFlow/ignitus-InterestFlow/Components/index.tsx
  src/ignitus-Authentication/ignitus-StudentSignUpFlow/ignitus-WelcomeFlow/Components/index.tsx
  src/ignitus-Authentication/ignitus-StudentSignUpFlow/ignitus-WelcomeFlow/Styles/style.ts
  src/ignitus-Authentication/ignitus-StudentSignUpFlow/index.tsx
  src/ignitus-Authentication/ignitus-StudentSignUpFlow/style.ts
  src/ignitus-Routes/ignitus-AuthenticationRoutes/index.tsx
Labels: PR: partially-approved

#889 fixed the join link in Nav menu
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-Navigation/Components/index.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-Navigation/constants.ts
Labels: PR: partially-approved

#896 updated all unit tests
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Molecules/ignitus-Modal/ignitus-ModalHooray/Components/__snapshots__/index.test.tsx.snap
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Molecules/ignitus-Modal/ignitus-ModalHooray/Components/index.test.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Molecules/ignitus-ToggleButtons/Components/ToggleButtoninterface.test.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Molecules/ignitus-ToggleButtons/Components/__snapshots__/ToggleButtoninterface.test.tsx.snap
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Molecules/ignitus-ToggleButtons/Components/__snapshots__/index.test.tsx.snap
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Molecules/ignitus-ToggleButtons/Components/index.test.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-DashBoardOpportunity/Components/DashBoardOpportunity.test.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-DashBoardOpportunity/Components/__snapshots__/DashBoardOpportunity.test.tsx.snap
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-DashboardFooter/Components/__snapshots__/index.test.tsx.snap
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-DashboardFooter/Components/index.test.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-OpportunityList/Components/__snapshots__/index.test.tsx.snap
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-OpportunityList/Components/index.test.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-ProfileCard/Components/__snapshots__/index.test.tsx.snap
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-ProfileCard/Components/index.test.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-SideNavigation/Common/Layer.test.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-SideNavigation/Common/__snapshots__/Layer.test.tsx.snap
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-SideProfileCard/Components/__snapshots__/index.test.tsx.snap
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-SideProfileCard/Components/index.test.tsx
Labels: PR: partially-approved, PR: unreviewed

#895 updated unit tests for ignitus-Atom
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultButtonWithIcon/Components/__snapshots__/index.test.tsx.snap
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultButtonWithIcon/Components/index.test.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultCheckbox/Components/__snapshots__/index.test.tsx.snap
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultCheckbox/Components/index.test.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultDropdown/Components/__snapshots__/index.test.tsx.snap
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultDropdown/Components/index.test.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultIconInput/Components/defaultIconInput/__snapshots__/index.test.tsx.snap
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultIconInput/Components/defaultIconInput/index.test.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultIconInput/Components/defaultPasswordInput/__snapshots__/index.test.tsx.snap
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultIconInput/Components/defaultPasswordInput/index.test.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultInput/Components/__snapshots__/index.test.tsx.snap
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultInput/Components/index.test.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultMulti/Components/__snapshots__/index.test.tsx.snap
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultMulti/Components/index.test.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultSearchInput/Components/__snapshots__/index.test.tsx.snap
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultSearchInput/Components/index.test.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultTag/Components/__snapshots__/defaultTag.test.tsx.snap
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultTag/Components/defaultTag.test.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-secondaryDropDown/Components/__snapshots__/index.test.tsx.snap
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-secondaryDropDown/Components/index.test.tsx
Labels: PR: partially-approved, PR: unreviewed

#832 Opportunity Details Page
  src/ignitus-Authentication/ignitus-CommonLoginInterface/sagas.ts
  src/ignitus-Dashboard/ignitus-Opportunity/ignitus-OpportunityDetails/Components/index.tsx
  src/ignitus-Dashboard/ignitus-Opportunity/ignitus-OpportunityDetails/constants.ts
  src/ignitus-Dashboard/ignitus-Opportunity/ignitus-OpportunityDetails/styles.ts
  src/ignitus-Routes/ignitus-DashboardRoutes/index.tsx
  src/ignitus-Routes/ignitus-UserInterfaceBookRoutes/index.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Assets/ignitus-Icons/checkIcon/index.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Assets/ignitus-Icons/shareIcon/index.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Assets/ignitus-Images/img-Png/UniversityOfMelbourne.png
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Assets/ignitus-Images/img-Png/share.png
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultIconInput/Components/defaultIconInput/index.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultIconInput/Components/defaultPasswordInput/index.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-DashBoardOpportunity/Components/__snapshots__/DashBoardOpportunity.test.tsx.snap
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-DashBoardOpportunity/style.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-OpportunitySideCard/Components/index.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-OpportunitySideCard/styles.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-OpportunitySideCard/types.ts
  src/ignitus-Shared/ignitus-Utilities/Components/icon.tsx
  src/ignitus-Shared/types/iconsTypes/iconEnums.ts
  src/ignitus-UserInterfaceBook/Components/Organisms/interfaceOpportunitySideCard/Components/index.tsx
Labels: PR: unreviewed

#866 Dashboard Nav Dropdown
  jest.config.js
  package-lock.json
  package.json
  src/ignitus-Routes/ignitus-UserInterfaceBookRoutes/index.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-navDropdown/Components/index.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-navDropdown/styles.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-navDropdown/types.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-SideNavigation/Common/__snapshots__/Layer.test.tsx.snap
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-SideNavigation/Common/styles.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-SideNavigation/Common/types.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-SideNavigation/ignitus-DashboardSideNavigation/style.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-SideNavigation/ignitus-MessageSideNavigation/style.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-SideNavigation/ignitus-UserSettingsSideNavigation/Components/index.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-SideNavigation/ignitus-UserSettingsSideNavigation/style.ts
  src/ignitus-UserInterfaceBook/Components/Atoms/interfaceNavDropdown/Components/index.tsx
  src/ignitus-UserInterfaceBook/Components/Atoms/interfaceNavDropdown/constants.ts
  src/ignitus-UserInterfaceBook/InterfaceSideNavigation/constants.ts
Labels: PR: partially-approved

#898 Added Notifications component under Organisms route
  src/ignitus-Routes/ignitus-UserInterfaceBookRoutes/index.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-Notifications/Components/index.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-Notifications/styles.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-Notifications/types.ts
  src/ignitus-Shared/index.ts
  src/ignitus-UserInterfaceBook/Components/Organisms/interfaceNotifications/Components/index.tsx
  src/ignitus-UserInterfaceBook/Components/Organisms/interfaceNotifications/style.ts
  src/ignitus-UserInterfaceBook/InterfaceSideNavigation/constants.ts
Labels: PR: unreviewed

#890 added unit test for Overlay component
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Molecules/ignitus-Overlay/Components/__snapshots__/index.test.tsx.snap
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Molecules/ignitus-Overlay/Components/index.test.tsx
Labels: PR: partially-approved

#901 Master > Develop
  src/ignitus-Api/index.js
  src/ignitus-Authentication/ignitus-CommonSignupInterface/actions.ts
  src/ignitus-Authentication/ignitus-CommonSignupInterface/sagas.ts
  src/ignitus-Authentication/ignitus-ProfessorLogin/Components/index.tsx
  src/ignitus-Authentication/ignitus-ProfessorSignUp/Components/index.tsx
  src/ignitus-Authentication/ignitus-StudentLogin/Components/index.tsx
  src/ignitus-Authentication/ignitus-StudentLogin/types.ts
  src/ignitus-Authentication/ignitus-StudentSignUpFlow/ignitus-StudentSignUp/Components/index.tsx
  src/ignitus-Dashboard/ignitus-DashboardHeader/Components/index.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Templates/ignitus-Authentication/Components/SplittedComponents/FormComponent/index.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Templates/ignitus-Authentication/statePayLoad.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Templates/ignitus-Authentication/styles.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Templates/ignitus-Authentication/types.ts
Labels: PR: unreviewed, release
