Repository Ignitus/Ignitus-client, pull requests merged in 2020-05, with the labels that each got.

#818 Career page view
  src/ignitus-CareersPage/Components/index.tsx
  src/ignitus-CareersPage/constants.ts
  src/ignitus-CareersPage/styles.ts
  src/ignitus-CareersPage/types.ts
  src/ignitus-Routes/ignitus-PublicRoutes/index.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Assets/ignitus-Icons/SearchIcon/index.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Assets/ignitus-Icons/searchIcon/index.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Assets/ignitus-Images/img-Svg/confetti.svg
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultSearchInput/Components/defaultSearchInput.test.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/typography.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Molecules/ignitus-Overlay/styles.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-Footer/Components/index.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Templates/ignitus-filterComponents/OpportunityFilters/OpportunityFilters.jsx
  src/ignitus-Shared/ignitus-Utilities/Components/icon.tsx
Labels: PR: unreviewed

#823 Master > Develop
  src/ignitus-CareersPage/Components/index.tsx
  src/ignitus-CareersPage/constants.ts
  src/ignitus-CareersPage/styles.ts
  src/ignitus-CareersPage/types.ts
  src/ignitus-Routes/ignitus-PublicRoutes/index.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Assets/ignitus-Icons/SearchIcon/index.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Assets/ignitus-Icons/searchIcon/index.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Assets/ignitus-Images/img-Svg/confetti.svg
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultSearchInput/Components/defaultSearchInput.test.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/typography.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Molecules/ignitus-Overlay/styles.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-Footer/Components/index.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Templates/ignitus-filterComponents/OpportunityFilters/OpportunityFilters.jsx
  src/ignitus-Shared/ignitus-Utilities/Components/icon.tsx
Labels: PR: unreviewed

#822 Unit test for ignitus-Overlay
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Molecules/ignitus-Overlay/Components/__snapshots__/index.test.tsx.snap
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Molecules/ignitus-Overlay/Components/index.test.tsx
Labels: PR: partially-approved

#817 Content change in Sign-up button
  src/ignitus-HomePage/ignitus-GetStarted/Components/index.tsx
  src/ignitus-HomePage/ignitus-Introduction/Components/index.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Molecules/ignitus-Overlay/Components/__snapshots__/index.test.tsx.snap
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Templates/ignitus-Authentication/Components/SplittedComponents/FormComponent/index.tsx
Labels: PR: unreviewed

#829 [ignitus-sideNavigation]: Refactoring
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-SideNavigation/Common/Layer.test.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-SideNavigation/Common/Layer.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-SideNavigation/Common/__snapshots__/Layer.test.tsx.snap
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-SideNavigation/Common/styles.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-SideNavigation/Common/types.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-SideNavigation/ignitus-DashboardSideNavigation/Components/index.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-SideNavigation/ignitus-DashboardSideNavigation/style.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-SideNavigation/ignitus-MessageSideNavigation/Components/index.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-SideNavigation/ignitus-MessageSideNavigation/style.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-SideNavigation/ignitus-UserSettingsSideNavigation/Components/index.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-SideNavigation/ignitus-UserSettingsSideNavigation/style.ts
  src/ignitus-Shared/index.ts
Labels: PR: partially-approved

#826 added test for secondary-dropdown
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-secondaryDropDown/Components/__snapshots__/index.test.tsx.snap
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-secondaryDropDown/Components/index.test.tsx
Labels: PR: partially-approved

#825 unit test for dashboardFooter
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-DashboardFooter/Components/__snapshots__/index.test.tsx.snap
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-DashboardFooter/Components/index.test.tsx
Labels: PR: partially-approved

#824 Master > Develop
  package-lock.json
  src/ignitus-Api/index.js
  src/ignitus-Authentication/ignitus-CommonLoginInterface/sagas.ts
  src/ignitus-HomePage/ignitus-GetStarted/Components/index.tsx
  src/ignitus-HomePage/ignitus-Introduction/Components/index.tsx
  src/ignitus-Routes/ignitus-UserInterfaceBookRoutes/index.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Assets/ignitus-Icons/barsIcon/barsIcon.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Assets/ignitus-Icons/barsIcon/index.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Assets/ignitus-Icons/gridIcon/gridIcon.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Assets/ignitus-Icons/gridIcon/index.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-secondaryDropDown/Components/__snapshots__/index.test.tsx.snap
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-secondaryDropDown/Components/index.test.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Molecules/ignitus-Overlay/Components/__snapshots__/index.test.tsx.snap
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Molecules/ignitus-Overlay/Components/index.test.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Molecules/ignitus-ToggleButtons/Components/ToggleButtoninterface.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Molecules/ignitus-ToggleButtons/Components/index.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Molecules/ignitus-ToggleButtons/styles.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Molecules/ignitus-ToggleButtons/types.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-DashboardFooter/Components/__snapshots__/index.test.tsx.snap
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-DashboardFooter/Components/index.test.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-SideNavigation/Common/Layer.test.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-SideNavigation/Common/Layer.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-SideNavigation/Common/__snapshots__/Layer.test.tsx.snap
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-SideNavigation/Common/styles.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-SideNavigation/Common/types.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-SideNavigation/ignitus-DashboardSideNavigation/Components/index.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-SideNavigation/ignitus-DashboardSideNavigation/style.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-SideNavigation/ignitus-MessageSideNavigation/Components/index.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-SideNavigation/ignitus-MessageSideNavigation/style.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-SideNavigation/ignitus-UserSettingsSideNavigation/Components/index.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-SideNavigation/ignitus-UserSettingsSideNavigation/style.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Templates/ignitus-Authentication/Components/SplittedComponents/FormComponent/index.tsx
  src/ignitus-Shared/ignitus-Utilities/Components/icon.tsx
  src/ignitus-Shared/ignitus-Utilities/reactHooks/setActiveHook.ts
  src/ignitus-Shared/index.ts
  src/ignitus-Shared/types/iconsTypes/iconEnums.ts
  src/ignitus-UserInterfaceBook/Components/Molecules/interfaceToggleButtons/Components/index.tsx
  src/ignitus-UserInterfaceBook/InterfaceSideNavigation/constants.ts
Labels: PR: unreviewed

#837 added test for ignitus-DashBoardOpportunity
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-DashBoardOpportunity/Components/DashBoardOpportunity.test.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-DashBoardOpportunity/Components/DashBoardOpportunity.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-DashBoardOpportunity/Components/__snapshots__/DashBoardOpportunity.test.tsx.snap
Labels: PR: partially-approved

#830 Added Scroll Bar component
  src/ignitus-Routes/ignitus-UserInterfaceBookRoutes/index.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Molecules/ignitus-ScrollBar/Components/index.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Molecules/ignitus-ScrollBar/styles.ts
  src/ignitus-Shared/index.ts
  src/ignitus-UserInterfaceBook/Components/Molecules/interfaceScrollBar/Components/index.tsx
  src/ignitus-UserInterfaceBook/InterfaceSideNavigation/constants.ts
Labels: PR: unreviewed

#839 Added test for avatars
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-Avatar/Components/Avatar.test.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-Avatar/Components/Avatar.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-Avatar/types.ts
Labels: PR: partially-approved

#841 Added test for ignitus-UnderConstruction
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Layout/ignitus-UnderContruction/Components/__snapshots__/index.test.tsx.snap
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Layout/ignitus-UnderContruction/Components/index.test.tsx
Labels: PR: partially-approved, easy, gssoc20

#840 Added test for ignitus-NotFound
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Layout/ignitus-NotFound/Components/__snapshots__/index.test.tsx.snap
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Layout/ignitus-NotFound/Components/index.test.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Layout/ignitus-NotFound/style.ts
Labels: PR: unreviewed

#836 Corrected opportunity typo and added test
  src/ignitus-Routes/ignitus-UserInterfaceBookRoutes/index.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-OpportunityList/Components/__snapshots__/index.test.tsx.snap
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-OpportunityList/Components/index.test.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-OpportunityList/Components/index.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-OpportunityList/styles.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-OppurtunityList/Components/OppurtunityList.tsx
  src/ignitus-Shared/index.ts
  src/ignitus-UserInterfaceBook/Components/Atoms/interfaceIcons/Components/index.tsx
  src/ignitus-UserInterfaceBook/Components/Layouts/interfaceSavedOpportunity/Components/index.tsx
  src/ignitus-UserInterfaceBook/Components/Organisms/interfaceOpportunity/Components/index.tsx
  src/ignitus-UserInterfaceBook/Components/Organisms/interfaceOpportunity/types.ts
  src/ignitus-UserInterfaceBook/Components/Organisms/interfaceOpportunityList/Components/index.tsx
  src/ignitus-UserInterfaceBook/Components/Organisms/interfaceOpportunityList/constants.ts
  src/ignitus-UserInterfaceBook/Components/Organisms/interfaceOpportunityList/types.ts
Labels: PR: partially-approved, easy, gssoc20, medium

#834 Added unit test for Side Profile
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-SideProfileCard/Components/__snapshots__/index.test.tsx.snap
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-SideProfileCard/Components/index.test.tsx
Labels: PR: partially-approved

#835 Added unit test for ignitus-ProfileCard
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-ProfileCard/Components/__snapshots__/index.test.tsx.snap
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-ProfileCard/Components/index.test.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-ProfileCard/Components/index.tsx
Labels: PR: partially-approved

#846 Added test for scroll bar
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Molecules/ignitus-ScrollBar/Components/__snapshots__/index.test.tsx.snap
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Molecules/ignitus-ScrollBar/Components/index.test.tsx
Labels: PR: partially-approved

#847 fixed document typos
  README.md
Labels: PR: partially-approved

#831 Added tests for ignitus-ToggleButtons
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Molecules/ignitus-ToggleButtons/Components/ToggleButtoninterface.test.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Molecules/ignitus-ToggleButtons/Components/__snapshots__/ToggleButtoninterface.test.tsx.snap
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Molecules/ignitus-ToggleButtons/Components/__snapshots__/index.test.tsx.snap
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Molecules/ignitus-ToggleButtons/Components/index.test.tsx
Labels: PR: partially-approved

#849 Moved to devDependencies 🔨
  package.json
Labels: PR: partially-approved

#842 Master > Develop
  README.md
  package.json
  src/ignitus-Routes/ignitus-UserInterfaceBookRoutes/index.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Layout/ignitus-NotFound/Components/__snapshots__/index.test.tsx.snap
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Layout/ignitus-NotFound/Components/index.test.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Layout/ignitus-NotFound/style.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Layout/ignitus-UnderContruction/Components/__snapshots__/index.test.tsx.snap
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Layout/ignitus-UnderContruction/Components/index.test.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Molecules/ignitus-ScrollBar/Components/__snapshots__/index.test.tsx.snap
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Molecules/ignitus-ScrollBar/Components/index.test.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Molecules/ignitus-ScrollBar/Components/index.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Molecules/ignitus-ScrollBar/styles.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Molecules/ignitus-ToggleButtons/Components/ToggleButtoninterface.test.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Molecules/ignitus-ToggleButtons/Components/__snapshots__/ToggleButtoninterface.test.tsx.snap
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Molecules/ignitus-ToggleButtons/Components/__snapshots__/index.test.tsx.snap
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Molecules/ignitus-ToggleButtons/Components/index.test.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-Avatar/Components/Avatar.test.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-Avatar/Components/Avatar.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-Avatar/types.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-DashBoardOpportunity/Components/DashBoardOpportunity.test.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-DashBoardOpportunity/Components/DashBoardOpportunity.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-DashBoardOpportunity/Components/__snapshots__/DashBoardOpportunity.test.tsx.snap
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-OpportunityList/Components/__snapshots__/index.test.tsx.snap
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-OpportunityList/Components/index.test.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-OpportunityList/Components/index.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-OpportunityList/styles.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-OppurtunityList/Components/OppurtunityList.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-ProfileCard/Components/__snapshots__/index.test.tsx.snap
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-ProfileCard/Components/index.test.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-ProfileCard/Components/index.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-SideProfileCard/Components/__snapshots__/index.test.tsx.snap
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-SideProfileCard/Components/index.test.tsx
  src/ignitus-Shared/index.ts
  src/ignitus-UserInterfaceBook/Components/Atoms/interfaceIcons/Components/index.tsx
  src/ignitus-UserInterfaceBook/Components/Layouts/interfaceSavedOpportunity/Components/index.tsx
  src/ignitus-UserInterfaceBook/Components/Molecules/interfaceScrollBar/Components/index.tsx
  src/ignitus-UserInterfaceBook/Components/Organisms/interfaceOpportunity/Components/index.tsx
  src/ignitus-UserInterfaceBook/Components/Organisms/interfaceOpportunity/types.ts
  src/ignitus-UserInterfaceBook/Components/Organisms/interfaceOpportunityList/Components/index.tsx
  src/ignitus-UserInterfaceBook/Components/Organisms/interfaceOpportunityList/constants.ts
  src/ignitus-UserInterfaceBook/Components/Organisms/interfaceOpportunityList/types.ts
  src/ignitus-UserInterfaceBook/InterfaceSideNavigation/constants.ts
Labels: PR: unreviewed

#848 Progress - migration to export const
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultButtonWithIcon/Components/__snapshots__/index.test.tsx.snap
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultButtonWithIcon/Components/index.test.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultButtonWithIcon/Components/index.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultButtonWithIcon/Components/index.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultCheckbox/Components/__snapshots__/index.test.tsx.snap
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultCheckbox/Components/index.test.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultCheckbox/Components/index.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultCheckbox/Components/index.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultDropdown/Components/__snapshots__/index.test.tsx.snap
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultDropdown/Components/index.test.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultDropdown/Components/index.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultDropdown/Components/index.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultIconInput/Components/defaultIconInput/__snapshots__/index.test.tsx.snap
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultIconInput/Components/defaultIconInput/index.test.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultIconInput/Components/defaultIconInput/index.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultIconInput/Components/defaultIconInput/index.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultIconInput/Components/defaultPasswordInput/__snapshots__/index.test.tsx.snap
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultIconInput/Components/defaultPasswordInput/index.test.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultInput/Components/__snapshots__/index.test.tsx.snap
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultInput/Components/index.test.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultInput/Components/index.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultInput/Components/index.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultMulti/Components/__snapshots__/index.test.tsx.snap
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultMulti/Components/index.test.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultMulti/Components/index.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultMulti/Components/index.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultSearchInput/Components/__snapshots__/index.test.tsx.snap
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultSearchInput/Components/index.test.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultSearchInput/Components/index.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultSearchInput/Components/index.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Molecules/ignitus-Overlay/Components/index.test.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Molecules/ignitus-Overlay/Components/index.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Molecules/ignitus-ScrollBar/Components/index.test.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Molecules/ignitus-ScrollBar/Components/index.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-Avatar/Components/index.test.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-Avatar/Components/index.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-Avatar/index.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-DashBoardOpportunity/Components/DashBoardOpportunity.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-DashboardFooter/Components/index.test.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-DashboardFooter/Components/index.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-SideNavigation/ignitus-DashboardSideNavigation/Components/index.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-SideNavigation/ignitus-MessageSideNavigation/Components/index.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-SideNavigation/ignitus-UserSettingsSideNavigation/Components/index.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Templates/ignitus-filterComponents/OpportunityFilters/styles.ts
  src/ignitus-Shared/index.ts
  src/ignitus-UserInterfaceBook/Components/Atoms/interfaceTags/Components/index.ts
  src/ignitus-UserInterfaceBook/Components/Atoms/interfaceTags/Components/index.tsx
Labels: PR: partially-approved

#838 Header icons
  src/ignitus-Dashboard/ignitus-DashboardHeader/Components/index.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Assets/ignitus-Icons/professorIcon/index.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Assets/ignitus-Icons/studentIcon/index.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-Navigation/styles.ts
  src/ignitus-Shared/ignitus-Utilities/Components/icon.tsx
  src/ignitus-Shared/types/iconsTypes/iconEnums.ts
Labels: PR: partially-approved

#853 Rename overlay to modal
  src/ignitus-Routes/ignitus-UserInterfaceBookRoutes/index.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Molecules/ignitus-Modal/Components/__snapshots__/index.test.tsx.snap
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Molecules/ignitus-Modal/Components/index.test.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Molecules/ignitus-Modal/Components/index.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Molecules/ignitus-Modal/styles.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Molecules/ignitus-Modal/types.ts
  src/ignitus-Shared/index.ts
  src/ignitus-UserInterfaceBook/Components/Molecules/interfaceModal/index.tsx
  src/ignitus-UserInterfaceBook/InterfaceSideNavigation/constants.ts
Labels: PR: merged

#851 Progress - replacing any with their types
  src/ignitus-AboutPage/ignitus-Team/actions.ts
  src/ignitus-AboutPage/ignitus-Team/types.ts
  src/ignitus-HomePage/ignitus-SupportedBy/types.ts
  src/ignitus-UserInterfaceBook/InterfaceSideNavigation/Components/index.tsx
  src/ignitus-UserInterfaceBook/InterfaceSideNavigation/types.ts
Labels: PR: partially-approved

#854 Progress - removing export default
  src/App.test.jsx
  src/App.tsx
  src/ignitus-AboutPage/ignitus-Team/Styles/index.ts
  src/ignitus-AboutPage/ignitus-Team/index.ts
  src/ignitus-AboutPage/ignitus-Team/reducers.ts
  src/ignitus-Authentication/ignitus-CommonLoginInterface/Containers/professorLogin.ts
  src/ignitus-Authentication/ignitus-CommonLoginInterface/Containers/studenLogin.ts
  src/ignitus-Authentication/ignitus-CommonLoginInterface/index.ts
  src/ignitus-Authentication/ignitus-CommonLoginInterface/reducer.ts
  src/ignitus-Authentication/ignitus-CommonSignupInterface/Containers/professorSignup.ts
  src/ignitus-Authentication/ignitus-CommonSignupInterface/Containers/studentSignup.ts
  src/ignitus-Authentication/ignitus-CommonSignupInterface/index.ts
  src/ignitus-Authentication/ignitus-CommonSignupInterface/reducers.ts
  src/ignitus-Authentication/ignitus-ProfessorLogin/Components/index.tsx
  src/ignitus-Authentication/ignitus-ProfessorSignUp/Components/index.tsx
  src/ignitus-Authentication/ignitus-StudentLogin/Components/index.tsx
  src/ignitus-Authentication/ignitus-StudentSignUpFlow/ignitus-EmailConfirmationFlow/Components/EmailConfirmationFlow.tsx
  src/ignitus-Authentication/ignitus-StudentSignUpFlow/ignitus-EmailConfirmationFlow/Components/index.ts
  src/ignitus-Authentication/ignitus-StudentSignUpFlow/ignitus-EmailConfirmationFlow/Components/index.tsx
  src/ignitus-Authentication/ignitus-StudentSignUpFlow/ignitus-EmailFlow/Components/index.ts
  src/ignitus-Authentication/ignitus-StudentSignUpFlow/ignitus-EmailFlow/Components/index.tsx
  src/ignitus-Authentication/ignitus-StudentSignUpFlow/ignitus-InterestFlow/Components/index.ts
  src/ignitus-Authentication/ignitus-StudentSignUpFlow/ignitus-InterestFlow/Components/index.tsx
  src/ignitus-Authentication/ignitus-StudentSignUpFlow/ignitus-StudentSignUp/Components/index.tsx
  src/ignitus-Authentication/ignitus-StudentSignUpFlow/ignitus-WelcomeFlow/Components/index.ts
  src/ignitus-Authentication/ignitus-StudentSignUpFlow/ignitus-WelcomeFlow/Components/index.tsx
  src/ignitus-Dashboard/ignitus-DashboardHeader/Components/index.tsx
  src/ignitus-Dashboard/ignitus-DashboardHeader/Containers/index.tsx
  src/ignitus-Dashboard/ignitus-DashboardHeader/constants.ts
  src/ignitus-HomePage/ignitus-Testimonial/index.ts
  src/ignitus-HomePage/ignitus-Testimonial/reducers.ts
  src/ignitus-Profile/ignitus-StudentProfile/styles.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultButtonWithIcon/styles.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultIconInput/Components/defaultPasswordInput/styles.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultIconInput/styles.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultMulti/styles.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultSearchInput/styles.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultTag/styles.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Molecules/ignitus-ToggleButtons/styles.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-Footer/styles.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-Navigation/styles.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-ProfileCard/styles.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-SideNavigation/ignitus-DashboardSideNavigation/style.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-SideProfileCard/styles.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Templates/ignitus-Authentication/styles.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Templates/ignitus-filterComponents/OpportunityFilters/OpportunityFilters.jsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Templates/ignitus-filterComponents/OpportunityFilters/styles.ts
  src/ignitus-Shared/ignitus-ErrorHandlingComponents/errorHandling/validate.js
  src/ignitus-Shared/ignitus-Utilities/Components/icon.tsx
  src/ignitus-Shared/index.ts
  src/ignitus-UserInterfaceBook/Components/Atoms/interfaceIcons/styles.ts
  src/ignitus-UserInterfaceBook/InterfaceSideNavigation/style.ts
  src/index.tsx
Labels: PR: unreviewed
