Repository Ignitus/Ignitus-client, pull requests merged in 2020-08, with the labels that each got.

#904 disabled eslint warnings
  .eslintrc.json
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultIconInput/Components/defaultIconInput/index.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultIconInput/Components/defaultPasswordInput/index.tsx
Labels: PR: partially-approved

#891 Added General Settings UI
  src/ignitus-Dashboard/ignitus-DashboardSettings/generalSettings/Components/index.tsx
  src/ignitus-Dashboard/ignitus-DashboardSettings/generalSettings/styles.ts
  src/ignitus-Routes/ignitus-DashboardRoutes/index.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultInput/Components/__snapshots__/index.test.tsx.snap
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultInput/styles.ts
Labels: PR: partially-approved

#899 Added detailsProfile page
  src/ignitus-Authentication/ignitus-StudentSignUpFlow/ignitus-DetailsProfileFlow/Components/index.tsx
  src/ignitus-Authentication/ignitus-StudentSignUpFlow/ignitus-DetailsProfileFlow/constants.ts
  src/ignitus-Authentication/ignitus-StudentSignUpFlow/ignitus-DetailsProfileFlow/style.ts
  src/ignitus-Authentication/ignitus-StudentSignUpFlow/ignitus-DetailsProfileFlow/types.ts
  src/ignitus-Authentication/ignitus-StudentSignUpFlow/index.tsx
  src/ignitus-Dashboard/ignitus-DashboardSettings/generalSettings/styles.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultCheckbox/Components/__snapshots__/index.test.tsx.snap
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultCheckbox/styles.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultIconInput/Components/defaultIconInput/__snapshots__/index.test.tsx.snap
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultIconInput/Components/defaultIconInput/index.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultIconInput/styles.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultIconInput/types.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultInput/Components/__snapshots__/index.test.tsx.snap
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultInput/Components/index.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultInput/styles.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultInput/types.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Molecules/ignitus-Modal/ignitus-ModalShare/Components/__snapshots__/index.test.tsx.snap
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Molecules/ignitus-Modal/ignitus-ModalShare/Components/index.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Templates/ignitus-Authentication/Components/SplittedComponents/FormComponent/index.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Templates/ignitus-Authentication/styles.ts
  src/ignitus-UserInterfaceBook/Components/Atoms/interfaceIconInput/Components/index.tsx
  src/ignitus-UserInterfaceBook/Components/Atoms/interfaceInput/Components/index.tsx
Labels: PR: partially-approved

#917 allowed indexing of ignitus.org
  public/robots.txt
Labels: PR: partially-approved

#916 added preload to webfonts
  public/index.html
  src/App.css
Labels: PR: partially-approved

#912 added test for message component
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-MessageCard/Components/__snapshots__/index.test.tsx.snap
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-MessageCard/Components/index.test.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-MessageCard/Components/index.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-MessageCard/types.ts
Labels: PR: partially-approved

#923 added modalApply component
  src/ignitus-Routes/ignitus-UserInterfaceBookRoutes/index.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Molecules/ignitus-Modal/ignitus-ModalApply/Components/index.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Molecules/ignitus-Modal/ignitus-ModalApply/styles.ts
  src/ignitus-Shared/index.ts
  src/ignitus-UserInterfaceBook/Components/Molecules/interfaceModalApply/Components/index.tsx
  src/ignitus-UserInterfaceBook/InterfaceSideNavigation/constants.ts
Labels: PR: partially-approved

#913 added test for notification component
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-Notifications/Components/__snapshots__/index.test.tsx.snap
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-Notifications/Components/index.test.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-Notifications/Components/index.tsx
Labels: PR: partially-approved

#934 Fixed component opportunitySideCard not listed under Organisms
  src/ignitus-UserInterfaceBook/Components/Organisms/interfaceOpportunitySideCard/Components/index.tsx
  src/ignitus-UserInterfaceBook/InterfaceSideNavigation/constants.ts
Labels: PR: reviewed-approved

#937 unit test for component loader
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-Loader/Components/__snapshots__/index.test.tsx.snap
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-Loader/Components/index.test.tsx
Labels: PR: partially-approved

#939 unit test for modal apply
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Molecules/ignitus-Modal/ignitus-ModalApply/Components/__snapshots__/index.test.tsx.snap
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Molecules/ignitus-Modal/ignitus-ModalApply/Components/index.test.tsx
Labels: PR: reviewed-approved

#911 added message Detail component
  src/ignitus-Routes/ignitus-UserInterfaceBookRoutes/index.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Assets/ignitus-Icons/forwardArrowIcon/index.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/colors.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-MessageDetail/Components/index.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-MessageDetail/styles.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-MessageDetail/types.ts
  src/ignitus-Shared/ignitus-Utilities/Components/icon.tsx
  src/ignitus-Shared/index.ts
  src/ignitus-Shared/types/iconsTypes/iconEnums.ts
  src/ignitus-UserInterfaceBook/Components/Atoms/interfaceIcons/constants.ts
  src/ignitus-UserInterfaceBook/Components/Organisms/interfaceMessageDetail/Components/index.tsx
  src/ignitus-UserInterfaceBook/Components/Organisms/interfaceMessageDetail/constants.ts
  src/ignitus-UserInterfaceBook/Components/Organisms/interfaceMessageDetail/types.ts
  src/ignitus-UserInterfaceBook/InterfaceSideNavigation/constants.ts
Labels: PR: unreviewed

#914 Added deleteAccount component
  src/ignitus-Authentication/ignitus-StudentSignUpFlow/ignitus-DetailsProfileFlow/style.ts
  src/ignitus-Authentication/ignitus-StudentSignUpFlow/ignitus-InterestFlow/Components/index.tsx
  src/ignitus-Routes/ignitus-UserInterfaceBookRoutes/index.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultCheckbox/Components/__snapshots__/index.test.tsx.snap
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultCheckbox/Components/index.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultCheckbox/styles.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultCheckbox/types.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultDropdown/Components/__snapshots__/index.test.tsx.snap
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultDropdown/Components/index.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-DeleteAccount/Components/index.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-DeleteAccount/styles.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-DeleteAccount/types.ts
  src/ignitus-Shared/index.ts
  src/ignitus-UserInterfaceBook/Components/Atoms/interfaceCheckBox/Components/index.tsx
  src/ignitus-UserInterfaceBook/Components/Organisms/interfaceDeleteAccount/Components/index.tsx
  src/ignitus-UserInterfaceBook/InterfaceSideNavigation/constants.ts
Labels: PR: reviewed-approved

#918 added preconnect in links to preconnect to required origins
  public/index.html
Labels: PR: partially-approved

#915 Added deleteFinal component
  src/ignitus-Routes/ignitus-UserInterfaceBookRoutes/index.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-DeleteFinal/Components/index.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-DeleteFinal/styles.ts
  src/ignitus-Shared/index.ts
  src/ignitus-UserInterfaceBook/Components/Organisms/interfaceDeleteFinal/Components/index.tsx
  src/ignitus-UserInterfaceBook/InterfaceSideNavigation/constants.ts
Labels: PR: partially-approved

#926 Added savedJobs component
  src/ignitus-Routes/ignitus-UserInterfaceBookRoutes/index.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Assets/ignitus-Icons/moreHorizontalIcon/index.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/colors.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-SavedJobsCard/Components/index.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-SavedJobsCard/styles.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-SavedJobsCard/types.ts
  src/ignitus-Shared/ignitus-Utilities/Components/icon.tsx
  src/ignitus-Shared/index.ts
  src/ignitus-Shared/types/iconsTypes/iconEnums.ts
  src/ignitus-UserInterfaceBook/Components/Atoms/interfaceIcons/constants.ts
  src/ignitus-UserInterfaceBook/Components/Organisms/interfaceSavedJobs/Components/index.tsx
  src/ignitus-UserInterfaceBook/Components/Organisms/interfaceSavedJobs/constants.ts
  src/ignitus-UserInterfaceBook/Components/Organisms/interfaceSavedJobs/types.ts
  src/ignitus-UserInterfaceBook/InterfaceSideNavigation/constants.ts
Labels: PR: partially-approved

#941 test: dashboard nav dropdown
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-navDropdown/Components/__snapshots__/index.test.tsx.snap
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-navDropdown/Components/index.test.tsx
Labels: PR: unreviewed

#942 Fixing the issue for redirect for smaller screen when clicking on navbar
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-Navigation/styles.ts
Labels: PR: partially-approved
