Repository Ignitus/Ignitus-client, pull requests merged in 2020-04, with the labels that each got.

#727 [Interface Book]: Separate scroll of Side navigation & Content
  src/ignitus-Routes/ignitus-UserInterfaceBookRoutes/index.jsx
  src/ignitus-UserInterfaceBook/InterfaceSideNavigation/style.ts
Labels: PR: partially-approved

#724 Removed Prop-Types in some components. 🔨
  src/ignitus-AboutPage/ignitus-CoreTeam/Components/team.tsx
  src/ignitus-Authentication/ignitus-StudentLogin/Components/Login.jsx
  src/ignitus-Authentication/ignitus-StudentSignUpFlow/ignitus-StudentSignUp/Components/SignUp.tsx
  src/ignitus-Careers/ignitus-JobConfirmation/Components/JobConfirmation.jsx
  src/ignitus-Dashboard/ignitus-DashboardHeader/Components/dashBoardHeader.js
Labels: PR: partially-approved

#733 Interface navigation implemented using recursion 🔨.
  src/ignitus-UserInterfaceBook/InterfaceSideNavigation/Components/interfaceSideNavigation.tsx
  src/ignitus-UserInterfaceBook/InterfaceSideNavigation/constants.ts
  src/ignitus-UserInterfaceBook/InterfaceSideNavigation/types.ts
Labels: PR: unreviewed

#738 [UserInterfaceBook]: Proper indentation on nesting.
  .github/auto_assign.yml
  src/ignitus-UserInterfaceBook/InterfaceSideNavigation/Components/interfaceSideNavigation.tsx
  src/ignitus-UserInterfaceBook/InterfaceSideNavigation/style.ts
  src/ignitus-UserInterfaceBook/InterfaceSideNavigation/types.ts
Labels: PR: unreviewed

#739 New feature - dashboard footer ★
  src/ignitus-Routes/ignitus-UserInterfaceBookRoutes/index.jsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-DashboardFooter/Components/index.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-DashboardFooter/style.ts
  src/ignitus-UserInterfaceBook/Components/Organisms/interfaceFooter/interfaceDashBoardFooter/Components/index.ts
  src/ignitus-UserInterfaceBook/Components/Organisms/interfaceFooter/interfaceDashBoardFooter/Components/interfaceDashBoardFooter.tsx
  src/ignitus-UserInterfaceBook/Components/Organisms/interfaceFooter/interfaceDashBoardFooter/style.ts
  src/ignitus-UserInterfaceBook/InterfaceSideNavigation/constants.ts
Labels: PR: unreviewed

#700 Altered Testimonial-carousel/UI 🎨
  src/ignitus-HomePage/ignitus-Testimonial/Components/Testimonial.jsx
  src/ignitus-HomePage/ignitus-Testimonial/Styles/style.scss
  src/ignitus-HomePage/ignitus-Testimonial/constants.js
  src/ignitus-HomePage/ignitus-Testimonial/images/i1.png
  src/ignitus-HomePage/ignitus-Testimonial/images/i2.png
  src/ignitus-HomePage/ignitus-Testimonial/images/i3.png
  src/ignitus-HomePage/ignitus-Testimonial/images/i4.png
Labels: PR: unreviewed

#741 Progress towards TypeScript. 🎓
  src/ignitus-Authentication/ignitus-ProfessorLogin/sagas.js
  src/ignitus-Authentication/ignitus-StudentLogin/Components/Login.tsx
  src/ignitus-Authentication/ignitus-StudentLogin/Components/index.ts
  src/ignitus-Authentication/ignitus-StudentLogin/types.ts
  src/ignitus-Authentication/ignitus-StudentSignUpFlow/ignitus-EmailConfirmationFlow/Components/EmailConfirmationFlow.tsx
  src/ignitus-Authentication/ignitus-StudentSignUpFlow/ignitus-EmailFlow/Components/EmailFlow.tsx
  src/ignitus-Authentication/ignitus-StudentSignUpFlow/ignitus-InterestFlow/Components/InterestFlow.tsx
  src/ignitus-Authentication/ignitus-StudentSignUpFlow/ignitus-StudentSignUp/Components/SignUp.tsx
  src/ignitus-Authentication/ignitus-StudentSignUpFlow/ignitus-StudentSignUp/types.ts
  src/ignitus-Authentication/ignitus-StudentSignUpFlow/ignitus-WelcomeFlow/Components/WelcomeFlow.tsx
  src/ignitus-Careers/ignitus-JobConfirmation/Components/JobConfirmation.tsx
  src/ignitus-Dashboard/ignitus-StudentDashboard/Components/Dashboard.tsx
  src/ignitus-HomePage/ignitus-Contributors/Components/Contributors.tsx
  src/ignitus-HomePage/ignitus-Partners/Components/Partners.tsx
  src/ignitus-HomePage/ignitus-Testimonial/Components/Testimonial.tsx
  src/ignitus-HomePage/ignitus-Testimonial/types.ts
  src/ignitus-HomePage/ignitus-WhatWeDo/Components/WhatWeDo.tsx
  src/ignitus-Routes/ignitus-PublicRoutes/index.tsx
  src/ignitus-Routes/ignitus-UserInterfaceBookRoutes/index.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-Footer/Components/Footer.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-Footer/types.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-Navigation/Components/Navigation.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-Navigation/types.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-OppurtunityList/Components/OppurtunityList.tsx
  src/ignitus-Shared/ignitus-ErrorHandlingComponents/errorBoundary/index.tsx
  src/ignitus-Shared/ignitus-ErrorHandlingComponents/errorBoundary/types.ts
  src/ignitus-UserInterfaceBook/Components/Atoms/interfaceButtons/Components/interfaceButtons.tsx
  src/ignitus-UserInterfaceBook/Components/Atoms/interfaceCards/Components/interfaceCards.tsx
  src/ignitus-UserInterfaceBook/Components/Atoms/interfaceCheckBox/Components/interfaceCheckBox.tsx
  src/ignitus-UserInterfaceBook/Components/Atoms/interfaceColors/Components/interfaceColors.tsx
  src/ignitus-UserInterfaceBook/Components/Atoms/interfaceDropDown/Components/interfaceDropDown.tsx
  src/ignitus-UserInterfaceBook/Components/Atoms/interfaceIcons/Components/interfaceIcons.tsx
  src/ignitus-UserInterfaceBook/Components/Atoms/interfaceInput/Components/interfaceInput.tsx
  src/ignitus-UserInterfaceBook/Components/Atoms/interfaceSearchInput/Components/interfaceSearchInput.tsx
  src/ignitus-UserInterfaceBook/Components/Atoms/interfaceSeparator/Components/interfaceSeparator.tsx
  src/ignitus-UserInterfaceBook/Components/Atoms/interfaceTypography/Components/interfaceTypography.tsx
  src/ignitus-UserInterfaceBook/Components/Layouts/interfaceNotFound/Components/interfaceNotFound.tsx
  src/ignitus-UserInterfaceBook/Components/Layouts/interfaceSavedOpportunity/Components/interfaceSavedOpportunity.tsx
  src/ignitus-UserInterfaceBook/Components/Layouts/interfaceUnderConstruction/Components/interfaceUnderConstruction.tsx
  src/ignitus-UserInterfaceBook/Components/Organisms/interfaceNavigation/Components/interfaceNavigation.tsx
  src/ignitus-UserInterfaceBook/Components/Organisms/interfaceOpportunity/Components/interfaceOpportunity.tsx
Labels: PR: partially-approved

#748 Remove unwanted space of sidebar.
  src/ignitus-Routes/ignitus-UserInterfaceBookRoutes/index.tsx
  src/ignitus-UserInterfaceBook/InterfaceSideNavigation/style.ts
Labels: PR: partially-approved

#745 Bugfix/signup page
  src/ignitus-Authentication/ignitus-StudentSignUpFlow/ignitus-StudentSignUp/Components/SignUp.tsx
Labels: PR: partially-approved

#749 Added publications input
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultIconInput/Components/defaultIconInput.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultIconInput/styles.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultIconInput/types.ts
  src/ignitus-UserInterfaceBook/Components/Atoms/interfaceIconInput/Components/interfaceIconInput.tsx
Labels: PR: unreviewed

#713 Hooray Overlay UI added
  src/ignitus-Routes/ignitus-UserInterfaceBookRoutes/index.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Assets/ignitus-Images/img-Svg/confetti.svg
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/atoms.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/colors.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultMulti/styles.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultSearchInput/styles.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Molecules/ignitus-Overlay/Components/index.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Molecules/ignitus-Overlay/styles.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Molecules/ignitus-Overlay/types.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-OppurtunityList/styles.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Templates/ignitus-filterComponents/OpportunityFilters/styles.ts
  src/ignitus-Shared/ignitus-Utilities/HelperFunctions/emotionHelpers.ts
  src/ignitus-UserInterfaceBook/Components/Atoms/interfaceColors/constants.ts
  src/ignitus-UserInterfaceBook/Components/Atoms/interfaceSeparator/styles.ts
  src/ignitus-UserInterfaceBook/Components/Molecules/interfaceOverlay/Components/index.ts
  src/ignitus-UserInterfaceBook/Components/Molecules/interfaceOverlay/Components/interfaceOverlay.tsx
  src/ignitus-UserInterfaceBook/Components/Molecules/interfaceOverlay/styles.ts
Labels: PR: partially-approved

#755 Job to automatic generate preview of pull request 🤖
  .github/workflows/pr-preview.yml
  scripts/deploy-preview/deploy.js
  scripts/deploy-preview/utils.js
  scripts/deploy-preview/verify.js
Labels: PR: partially-approved

#765 Flaky behavior of Student signup & login.
  src/ignitus-Authentication/ignitus-StudentLogin/Components/Login.tsx
  src/ignitus-Authentication/ignitus-StudentLogin/Containers/loginContainer.js
  src/ignitus-Authentication/ignitus-StudentLogin/actionTypes.js
  src/ignitus-Authentication/ignitus-StudentLogin/actions.js
  src/ignitus-Authentication/ignitus-StudentLogin/reducers.js
  src/ignitus-Authentication/ignitus-StudentLogin/types.ts
  src/ignitus-Authentication/ignitus-StudentSignUpFlow/ignitus-StudentSignUp/Components/SignUp.tsx
  src/ignitus-Authentication/ignitus-StudentSignUpFlow/ignitus-StudentSignUp/Containers/studentContainer.js
  src/ignitus-Authentication/ignitus-StudentSignUpFlow/ignitus-StudentSignUp/actionTypes.ts
  src/ignitus-Authentication/ignitus-StudentSignUpFlow/ignitus-StudentSignUp/actions.ts
  src/ignitus-Authentication/ignitus-StudentSignUpFlow/ignitus-StudentSignUp/reducers.ts
  src/ignitus-Authentication/ignitus-StudentSignUpFlow/ignitus-StudentSignUp/types.ts
Labels: PR: partially-approved

#763 [UIKit]: Expansion of text area inside Multimedia Input UI
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultMulti/Components/defaultMultiMediaInput.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultMulti/styles.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultMulti/types.ts
Labels: PR: partially-approved

#769 Profile Card UI ☘️
  src/ignitus-Routes/ignitus-PublicRoutes/index.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Assets/ignitus-Icons/bookmarkIcon/bookmarkIcon.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Assets/ignitus-Icons/bookmarkIcon/index.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Assets/ignitus-Icons/fileIcon/fileIcon.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Assets/ignitus-Icons/fileIcon/index.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Assets/ignitus-Icons/githubIcon/githubIcon.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Assets/ignitus-Icons/mapMarkerIcon/index.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Assets/ignitus-Icons/mapMarkerIcon/mapMarkerIcon.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-ProfileCard/Components/index.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-ProfileCard/styles.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-ProfileCard/types.ts
  src/ignitus-Shared/ignitus-Utilities/Components/icon.tsx
  src/ignitus-Shared/types/iconsTypes/iconEnums.ts
  src/ignitus-UserInterfaceBook/Components/Organisms/interfaceOpportunity/Components/interfaceOpportunity.tsx
  src/ignitus-UserInterfaceBook/Components/Organisms/interfaceOpportunity/style.ts
Labels: PR: unreviewed

#770 Progress - Migration to export const
  src/ignitus-UserInterfaceBook/Components/Atoms/interfaceButtons/Components/index.ts
  src/ignitus-UserInterfaceBook/Components/Atoms/interfaceButtons/Components/index.tsx
  src/ignitus-UserInterfaceBook/Components/Atoms/interfaceCards/Components/index.ts
  src/ignitus-UserInterfaceBook/Components/Atoms/interfaceCards/Components/index.tsx
  src/ignitus-UserInterfaceBook/Components/Atoms/interfaceCheckBox/Components/index.ts
  src/ignitus-UserInterfaceBook/Components/Atoms/interfaceCheckBox/Components/index.tsx
  src/ignitus-UserInterfaceBook/Components/Atoms/interfaceColors/Components/index.ts
  src/ignitus-UserInterfaceBook/Components/Atoms/interfaceColors/Components/index.tsx
  src/ignitus-UserInterfaceBook/Components/Atoms/interfaceDropDown/Components/index.ts
  src/ignitus-UserInterfaceBook/Components/Atoms/interfaceDropDown/Components/index.tsx
  src/ignitus-UserInterfaceBook/Components/Atoms/interfaceIconInput/Components/index.ts
  src/ignitus-UserInterfaceBook/Components/Atoms/interfaceIconInput/Components/index.tsx
  src/ignitus-UserInterfaceBook/Components/Atoms/interfaceIcons/Components/index.ts
  src/ignitus-UserInterfaceBook/Components/Atoms/interfaceIcons/Components/index.tsx
  src/ignitus-UserInterfaceBook/Components/Atoms/interfaceInput/Components/index.ts
  src/ignitus-UserInterfaceBook/Components/Atoms/interfaceInput/Components/index.tsx
  src/ignitus-UserInterfaceBook/Components/Atoms/interfaceMulti/Components/index.ts
  src/ignitus-UserInterfaceBook/Components/Atoms/interfaceMulti/Components/index.tsx
  src/ignitus-UserInterfaceBook/Components/Atoms/interfaceSearchInput/Components/index.ts
  src/ignitus-UserInterfaceBook/Components/Atoms/interfaceSearchInput/Components/index.tsx
  src/ignitus-UserInterfaceBook/Components/Atoms/interfaceSeparator/Components/index.ts
  src/ignitus-UserInterfaceBook/Components/Atoms/interfaceSeparator/Components/index.tsx
  src/ignitus-UserInterfaceBook/Components/Atoms/interfaceTypography/Components/index.ts
  src/ignitus-UserInterfaceBook/Components/Atoms/interfaceTypography/Components/index.tsx
  src/ignitus-UserInterfaceBook/Components/Layouts/interfaceNotFound/Components/index.ts
  src/ignitus-UserInterfaceBook/Components/Layouts/interfaceNotFound/Components/index.tsx
  src/ignitus-UserInterfaceBook/Components/Layouts/interfaceSavedOpportunity/Components/index.ts
  src/ignitus-UserInterfaceBook/Components/Layouts/interfaceSavedOpportunity/Components/index.tsx
  src/ignitus-UserInterfaceBook/Components/Layouts/interfaceUnderConstruction/Components/index.ts
  src/ignitus-UserInterfaceBook/Components/Layouts/interfaceUnderConstruction/Components/index.tsx
  src/ignitus-UserInterfaceBook/Components/Molecules/interfaceOverlay/Components/index.ts
  src/ignitus-UserInterfaceBook/Components/Molecules/interfaceOverlay/Components/index.tsx
  src/ignitus-UserInterfaceBook/Components/Organisms/interfaceFooter/interfaceDashBoardFooter/Components/index.ts
  src/ignitus-UserInterfaceBook/Components/Organisms/interfaceFooter/interfaceDashBoardFooter/Components/index.tsx
  src/ignitus-UserInterfaceBook/Components/Organisms/interfaceNavigation/Components/index.ts
  src/ignitus-UserInterfaceBook/Components/Organisms/interfaceNavigation/Components/index.tsx
  src/ignitus-UserInterfaceBook/Components/Organisms/interfaceOpportunity/Components/index.ts
  src/ignitus-UserInterfaceBook/Components/Organisms/interfaceOpportunity/Components/index.tsx
  src/ignitus-UserInterfaceBook/InterfaceSideNavigation/Components/index.ts
  src/ignitus-UserInterfaceBook/InterfaceSideNavigation/Components/index.tsx
Labels: PR: partially-approved

#772 fix: removed console warnings
  src/ignitus-AboutPage/ignitus-Team/Components/index.tsx
  src/ignitus-HomePage/ignitus-Testimonial/Components/index.tsx
  src/ignitus-HomePage/ignitus-Testimonial/sagas.ts
  src/ignitus-HomePage/ignitus-WhatWeDo/Components/index.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Layout/ignitus-NotFound/Components/index.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Layout/ignitus-UnderContruction/Components/index.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-Footer/Components/Footer.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-OppurtunityList/Components/OppurtunityList.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Templates/ignitus-Authentication/Components/SplittedComponents/SideWrapperComponent/index.tsx
  src/ignitus-UserInterfaceBook/Components/Atoms/interfaceIcons/Components/index.tsx
  src/ignitus-UserInterfaceBook/InterfaceSideNavigation/Components/index.tsx
Labels: PR: unreviewed

#764 Keep white background on navbar constant in Home and About page
  src/ignitus-Routes/ignitus-PublicRoutes/index.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-Navigation/Components/Navigation.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-Navigation/Styles/style.scss
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-Navigation/types.ts
Labels: PR: partially-approved

#777 Clear error message on unvisiting student Login page
  src/ignitus-Authentication/ignitus-StudentLogin/Components/Login.tsx
Labels: PR: partially-approved

#776 ESLint configuration updates
  .eslintrc
Labels: PR: partially-approved

#766 :bug: link to complete div instead of just image
  src/ignitus-Authentication/ignitus-CommonAuthenticationInterface/Components/index.tsx
Labels: PR: partially-approved, gssoc20

#781 fix(pr-preview): Fix error by performing force checkout.
  .github/workflows/pr-preview.yml
Labels: PR: partially-approved

#785 Design changes
  package-lock.json
  src/ignitus-AboutPage/ignitus-CoreTeam/styles.ts
  src/ignitus-AboutPage/ignitus-Team/Styles/index.ts
  src/ignitus-Dashboard/ignitus-DashboardHeader/Components/index.tsx
  src/ignitus-HomePage/ignitus-Contributors/styles.ts
  src/ignitus-HomePage/ignitus-SupportedBy/styles.ts
  src/ignitus-HomePage/ignitus-WhatWeDo/styles.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Assets/ignitus-Icons/chevronIcon/chevronIcon.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Assets/ignitus-Icons/chevronIcon/index.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Assets/ignitus-Icons/clearIcon/clearIcon.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Assets/ignitus-Icons/clearIcon/index.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Assets/ignitus-Icons/locationOnIcon/index.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Assets/ignitus-Icons/locationOnIcon/locationOnIcon.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/atoms.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/buttons.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/colors.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/fonts.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultMulti/styles.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/typography.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Layout/ignitus-DashBoardOpportunity/style.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Molecules/ignitus-Overlay/styles.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-DashboardFooter/style.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-Navigation/Components/index.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-Navigation/styles.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-OppurtunityList/styles.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-ProfileCard/styles.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-SideNavigation/ignitus-DashboardSideNavigation/style.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-SideNavigation/ignitus-MessageSideNavigation/style.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-SideNavigation/ignitus-UserSettingsSideNavigation/style.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Templates/ignitus-filterComponents/OpportunityFilters/styles.ts
  src/ignitus-Shared/ignitus-Utilities/Components/icon.tsx
  src/ignitus-Shared/types/iconsTypes/iconEnums.ts
  src/ignitus-UserInterfaceBook/Components/Atoms/interfaceIcons/constants.ts
  src/ignitus-UserInterfaceBook/InterfaceSideNavigation/constants.ts
Labels: PR: partially-approved

#782 Common Login for Professor and Student 🎓
  package-lock.json
  src/ignitus-AboutPage/ignitus-CoreTeam/styles.ts
  src/ignitus-Api/index.js
  src/ignitus-Authentication/ignitus-CommonLoginInterface/Containers/professorLogin.ts
  src/ignitus-Authentication/ignitus-CommonLoginInterface/Containers/studenLogin.ts
  src/ignitus-Authentication/ignitus-CommonLoginInterface/Containers/utils.ts
  src/ignitus-Authentication/ignitus-CommonLoginInterface/actionTypes.ts
  src/ignitus-Authentication/ignitus-CommonLoginInterface/actions.ts
  src/ignitus-Authentication/ignitus-CommonLoginInterface/constants.ts
  src/ignitus-Authentication/ignitus-CommonLoginInterface/index.ts
  src/ignitus-Authentication/ignitus-CommonLoginInterface/reducer.ts
  src/ignitus-Authentication/ignitus-CommonLoginInterface/sagas.ts
  src/ignitus-Authentication/ignitus-CommonLoginInterface/selectors.ts
  src/ignitus-Authentication/ignitus-ProfessorLogin/Components/index.tsx
  src/ignitus-Authentication/ignitus-ProfessorLogin/actionTypes.js
  src/ignitus-Authentication/ignitus-ProfessorLogin/actions.js
  src/ignitus-Authentication/ignitus-ProfessorLogin/constants.js
  src/ignitus-Authentication/ignitus-ProfessorLogin/reducers.js
  src/ignitus-Authentication/ignitus-ProfessorLogin/sagas.js
  src/ignitus-Authentication/ignitus-ProfessorLogin/selectors.js
  src/ignitus-Authentication/ignitus-StudentLogin/Components/index.tsx
  src/ignitus-Authentication/ignitus-StudentLogin/Containers/index.ts
  src/ignitus-Authentication/ignitus-StudentLogin/constants.js
  src/ignitus-Authentication/ignitus-StudentLogin/index.js
  src/ignitus-Authentication/ignitus-StudentLogin/types.ts
  src/ignitus-Authentication/ignitus-StudentSignUpFlow/ignitus-StudentSignUp/Components/index.tsx
  src/ignitus-Dashboard/ignitus-DashboardHeader/Containers/index.tsx
  src/ignitus-Routes/ignitus-AuthenticationRoutes/index.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultIconInput/Components/defaultIconInput/defaultIconInput.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultIconInput/Components/defaultPasswordInput/index.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultIconInput/types.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Templates/ignitus-Authentication/Components/SplittedComponents/FormComponent/index.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Templates/ignitus-Authentication/Components/styles.ts
  src/ignitus-UserInterfaceBook/Components/Atoms/interfaceIconInput/Components/index.tsx
  src/rootReducer.ts
  src/rootSagas.ts
Labels: PR: unreviewed

#788 Common Signup internals for Professor and Student
  src/ignitus-Api/index.js
  src/ignitus-Authentication/ignitus-CommonSignupInterface/Containers/professorSignup.ts
  src/ignitus-Authentication/ignitus-CommonSignupInterface/Containers/studentSignup.ts
  src/ignitus-Authentication/ignitus-CommonSignupInterface/Containers/utils.ts
  src/ignitus-Authentication/ignitus-CommonSignupInterface/actionTypes.ts
  src/ignitus-Authentication/ignitus-CommonSignupInterface/actions.ts
  src/ignitus-Authentication/ignitus-CommonSignupInterface/constants.ts
  src/ignitus-Authentication/ignitus-CommonSignupInterface/index.ts
  src/ignitus-Authentication/ignitus-CommonSignupInterface/reducers.ts
  src/ignitus-Authentication/ignitus-CommonSignupInterface/sagas.ts
  src/ignitus-Authentication/ignitus-CommonSignupInterface/selectors.ts
  src/ignitus-Authentication/ignitus-ProfessorSignUp/Components/index.tsx
  src/ignitus-Authentication/ignitus-ProfessorSignUp/Containers/index.ts
  src/ignitus-Authentication/ignitus-ProfessorSignUp/actionTypes.ts
  src/ignitus-Authentication/ignitus-ProfessorSignUp/actions.ts
  src/ignitus-Authentication/ignitus-ProfessorSignUp/constants.ts
  src/ignitus-Authentication/ignitus-ProfessorSignUp/reducers.ts
  src/ignitus-Authentication/ignitus-ProfessorSignUp/sagas.ts
  src/ignitus-Authentication/ignitus-ProfessorSignUp/selectors.ts
  src/ignitus-Authentication/ignitus-ProfessorSignUp/types.ts
  src/ignitus-Authentication/ignitus-StudentLogin/index.ts
  src/ignitus-Authentication/ignitus-StudentSignUpFlow/ignitus-StudentSignUp/Components/index.tsx
  src/ignitus-Authentication/ignitus-StudentSignUpFlow/ignitus-StudentSignUp/Containers/index.ts
  src/ignitus-Authentication/ignitus-StudentSignUpFlow/ignitus-StudentSignUp/constants.ts
  src/ignitus-Authentication/ignitus-StudentSignUpFlow/ignitus-StudentSignUp/index.ts
  src/ignitus-Authentication/ignitus-StudentSignUpFlow/ignitus-StudentSignUp/selectors.ts
  src/ignitus-Authentication/ignitus-StudentSignUpFlow/ignitus-StudentSignUp/types.ts
  src/ignitus-Routes/ignitus-AuthenticationRoutes/index.tsx
  src/rootReducer.ts
  src/rootSagas.ts
Labels: PR: partially-approved

#792 [ignitus-Shared]: Added Link component
  src/ignitus-Shared/ignitus-Utilities/Components/Link/index.tsx
  src/ignitus-Shared/ignitus-Utilities/Components/Link/link.test.tsx
  src/ignitus-Shared/ignitus-Utilities/Components/Link/utils.ts
Labels: PR: partially-approved

#794 fix: browser console error.
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-Navigation/styles.ts
  src/ignitus-UserInterfaceBook/InterfaceSideNavigation/style.ts
Labels: PR: partially-approved

#753 Profile Detail View UI
  package-lock.json
  src/ignitus-AboutPage/ignitus-Team/Components/index.tsx
  src/ignitus-AboutPage/ignitus-Team/Styles/index.ts
  src/ignitus-Dashboard/ignitus-StudentDashboard/styles.ts
  src/ignitus-HomePage/ignitus-Testimonial/style.ts
  src/ignitus-Profile/ignitus-StudentProfile/Components/index.tsx
  src/ignitus-Profile/ignitus-StudentProfile/styles.ts
  src/ignitus-Profile/ignitus-StudentProfile/types.ts
  src/ignitus-Routes/ignitus-DashboardRoutes/index.jsx
  src/ignitus-Routes/ignitus-PublicRoutes/index.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Assets/ignitus-Icons/conributionIcon/contributionIcon.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Assets/ignitus-Icons/conributionIcon/index.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Assets/ignitus-Icons/starCircleIcon/index.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Assets/ignitus-Icons/starCircleIcon/starCircleIcon.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/buttons.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/typography.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-Footer/Components/index.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-SideNavigation/ignitus-DashboardSideNavigation/style.ts
  src/ignitus-Shared/ignitus-Utilities/Components/icon.tsx
  src/ignitus-Shared/types/iconsTypes/iconEnums.ts
Labels: PR: partially-approved

#797 [ignitus-Shared]: Add Avatar component
  src/ignitus-Routes/ignitus-UserInterfaceBookRoutes/index.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-Avatar/Components/Avatar.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-Avatar/avatars.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-Avatar/index.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-Avatar/styles.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-Avatar/types.ts
  src/ignitus-UserInterfaceBook/Components/Organisms/interfaceAvatar/Components/index.tsx
  src/ignitus-UserInterfaceBook/InterfaceSideNavigation/constants.ts
Labels: PR: partially-approved

#798 fix: console error
  src/ignitus-HomePage/ignitus-Testimonial/reducers.ts
Labels: PR: partially-approved

#802 Dashboard Side Navigation Profile/UI
  src/ignitus-Routes/ignitus-UserInterfaceBookRoutes/index.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Molecules/index.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-SideProfileCard/Components/index.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-SideProfileCard/styles.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-SideProfileCard/types.ts
  src/ignitus-UserInterfaceBook/Components/Organisms/interfaceSideProfile/Components/index.tsx
  src/ignitus-UserInterfaceBook/InterfaceSideNavigation/constants.ts
Labels: PR: partially-approved

#803 [ignitus-Shared]: index file which contains all components.
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/atoms.ts
  src/ignitus-Shared/index.ts
Labels: PR: partially-approved

#800 [ignitus-UIBook]: Added Signup progress component.
  src/ignitus-Routes/ignitus-UserInterfaceBookRoutes/index.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Molecules/ignitus-Progress/Components/Progress.test.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Molecules/ignitus-Progress/Components/Progress.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Molecules/ignitus-Progress/index.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Molecules/ignitus-Progress/styles.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Molecules/ignitus-Progress/types.ts
  src/ignitus-UserInterfaceBook/Components/Molecules/interfaceProgress/index.tsx
  src/ignitus-UserInterfaceBook/InterfaceSideNavigation/constants.ts
Labels: PR: unreviewed

#783 feat: added tags component
  src/ignitus-Routes/ignitus-UserInterfaceBookRoutes/index.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/colors.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultTag/Components/defaultTag.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultTag/Components/index.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultTag/styles.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultTag/types.ts
  src/ignitus-UserInterfaceBook/Components/Atoms/interfaceTags/Components/index.ts
  src/ignitus-UserInterfaceBook/Components/Atoms/interfaceTags/Components/interfaceTags.tsx
  src/ignitus-UserInterfaceBook/Components/Atoms/interfaceTags/styles.ts
  src/ignitus-UserInterfaceBook/InterfaceSideNavigation/constants.ts
Labels: PR: unreviewed

#810 Readme change
  .github/auto_assign.yml
  README.md
Labels: PR: partially-approved

#812 [ignitus-Shared]: Unit tests
  package-lock.json
  package.json
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultButtonWithIcon/Components/__snapshots__/defaultButtonWithIcon.test.tsx.snap
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultButtonWithIcon/Components/defaultButtonWithIcon.test.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultCheckbox/Components/__snapshots__/defaultCheckbox.test.tsx.snap
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultCheckbox/Components/defaultCheckbox.test.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultDropdown/Components/__snapshots__/defaultDropdown.test.tsx.snap
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultDropdown/Components/defaultDropdown.test.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultIconInput/Components/defaultIconInput/__snapshots__/defaultIconInput.test.tsx.snap
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultIconInput/Components/defaultIconInput/defaultIconInput.test.tsx
Labels: PR: partially-approved

#809 Added buttons with icons on left
  package-lock.json
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/buttons.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultButtonWithIcon/Components/__snapshots__/defaultButtonWithIcon.test.tsx.snap
  src/ignitus-UserInterfaceBook/Components/Atoms/interfaceButtons/Components/index.tsx
Labels: PR: unreviewed

#808 Secondary Dropdown
  src/ignitus-Routes/ignitus-UserInterfaceBookRoutes/index.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-secondaryDropDown/Components/index.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-secondaryDropDown/styles.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-secondaryDropDown/types.ts
  src/ignitus-Shared/index.ts
  src/ignitus-UserInterfaceBook/Components/Atoms/interfaceSecondaryDropdown/Components/index.tsx
  src/ignitus-UserInterfaceBook/Components/Atoms/interfaceSecondaryDropdown/constants.ts
  src/ignitus-UserInterfaceBook/Components/Atoms/interfaceSecondaryDropdown/types.ts
  src/ignitus-UserInterfaceBook/InterfaceSideNavigation/constants.ts
Labels: PR: unreviewed

#813 Unit tests
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultIconInput/Components/defaultPasswordInput/__snapshots__/defaultPasswordInput.test.tsx.snap
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultIconInput/Components/defaultPasswordInput/defaultPasswordInput.test.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultIconInput/Components/defaultPasswordInput/index.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultIconInput/types.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultInput/Components/__snapshots__/defaultInput.test.tsx.snap
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultInput/Components/defaultInput.test.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultInput/Components/defaultInput.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultInput/types.ts
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultMulti/Components/__snapshots__/defaultMultiMediaInput.test.tsx.snap
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultMulti/Components/defaultMultiMediaInput.test.tsx
Labels: PR: partially-approved

#814 [ignitus-Shared/atoms]: unit tests
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultSearchInput/Components/__snapshots__/defaultSearchInput.test.tsx.snap
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultSearchInput/Components/defaultSearchInput.test.tsx
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultTag/Components/__snapshots__/defaultTag.test.tsx.snap
  src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultTag/Components/defaultTag.test.tsx
Labels: PR: partially-approved
